lib/asciidoctor/extensions.rb

I hope I understood what the code does ...

Fix inline_macro and block_macro documentation

---

lib/asciidoctor/cli/options.rb

FIX for List available backends

---

lib/asciidoctor.rb
test/links_test.rb

Make XrefInlineRx regexp more permissive.

---

lib/asciidoctor/parser.rb
test/tables_test.rb

- change split call to preserve empty records
- add test for colspec with empty records
- minor optimizations

resolves #1375 account for empty records in colspec

---

lib/asciidoctor/opal_ext/comparable.rb

- add implementation of !=
- apply code styles

resolves #1385 add implementation of != method to Opal

---

lib/asciidoctor/reader.rb
test/reader_test.rb

- always resolve missing attribute in ifeval expression to empty string
- add additional tests for ifeval
- code cleanups and formatting

resolves #1387 resolve missing attribute in ifeval to empty string

---

lib/asciidoctor/converter/html5.rb
test/blocks_test.rb

See http://www.html5rocks.com/en/tutorials/speed/script-loading/
Resolves #1238

Load script at the end of document

---

lib/asciidoctor/abstract_block.rb
test/document_test.rb

- block argument to find_by should be used to filter results
- find_by should return an empty array instead of nil if no results are found
- add a comprehensive set of tests for the find_by method

resolves #1393 block argument to find_by should filter results

---

lib/asciidoctor/converter/html5.rb
test/document_test.rb

- show manpage title & name section in embeddable HTML
- add test

resolves #1179 show manpage title & name section in embeddable HTML

---

lib/asciidoctor.rb
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/helpers.rb
lib/asciidoctor/path_resolver.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/substitutors.rb

- add Helpers.uriish? to check if String resembles URI
- add Helpers.uri_prefix to retrieve URI prefix pattern from string
- deprecate is_uri? method on AbstractNode
- minor optimizations

resolves #1422 introduce helper methods for sniffing URIs

---

data/stylesheets/asciidoctor-default.css

- add CSS class "center" to center block within parent container
- make the class "spread" generic for use on all blocks

resolves #1456 add CSS class for center block alignment

---

lib/asciidoctor/converter/html5.rb
test/document_test.rb

- insert docinfo footer content below footer div
- insert docinfo footer even if nofooter is set

resolves #1503 insert docinfo footer below footer div

---

lib/asciidoctor/document.rb
test/attributes_test.rb

- allows attributes to be overridden by API

resolves #1255 restore attributes after parse

---

lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/document.rb
lib/asciidoctor/extensions.rb
test/document_test.rb
test/extensions_test.rb

- use docinfo attribute to enable docinfo behavior
- rename :header docinfo location to :head

resolves #1510 use value of docinfo attribute to enable docinfo behavior

---

data/stylesheets/asciidoctor-default.css

- fix alignment of wrapped text
- slightly increase line height
- optimize text legibility
- tighten letter spacing of bold text

resolves #1524 fix alignment of wrapped text in footnote

---

CONTRIBUTING.adoc

Updated contributing guide to provide links to background knowledge.

---

lib/asciidoctor/reader.rb
test/reader_test.rb

- don't swallow line after include when file is not readable
- add test for when include file is not readable
- rename replace_line to replace_next_line to make intent more clear
- minor cleanups
- fix tomdoc

resolves #1602 don't swallow trailing line when include file is not readable

---

CHANGELOG.adoc
README-fr.adoc
_settings-README.adoc

Here is my gift ! :gift: 
@gscheibel could you make a review of the translation please ?
Merry christmas

feat(doc): add french version of the README

---

lib/asciidoctor/converter/html5.rb
test/blocks_test.rb

Addresses issue: https://github.com/asciidoctor/asciidoctor/issues/1723

upgrade font awesome to 4.6.1

---

data/locale/attributes.adoc

Added french translations for built-in labels

French translations for built-in labels

---

data/locale/attributes.adoc

I must admit I'm not sure how one would translate "Listing", but I guess using the English loanword is common today.

Translate Attributes to German

---

data/locale/attributes.adoc

Added arabic translations for built-in labels

Arabic translations for built-in labels

---

data/locale/attributes.adoc

I changed Table to Tableau, since it is more accurate.

changed according to remark on Tableau

---

data/locale/attributes.adoc

Added Persian (Farsi) translation to internal attributes.

added Persian (Farsi) translation to internal attributes.

---

lib/asciidoctor/converter/html5.rb
test/blocks_test.rb

Resolves #1774, Upgrade FontAwesome to 4.6.3

---

.travis.yml

updated ruby patch version to ensure it works well with latest ruby

updated ruby patch

---

data/locale/attributes.adoc

Hungarian translate.

---

data/locale/attributes.adoc

For both Cyrillic and Latin alphabet

Translate built-in attributes to Serbian

---

lib/asciidoctor/converter/template.rb

- Tilt attempts to load opal if it encounters a file that ends with .rb
- skip .rb files found in template directories to workaround problem (unless Ruby engine is Opal)

resolves #1827 skip .rb files in template directories

---

lib/asciidoctor/converter/html5.rb

- optimize check for xml mode by consulting @xml_mode instance variable

optimize check for xml mode

---

data/locale/attributes.adoc

Update fragment identifier: http://asciidoctor.org/docs/user-manual/#customizing-labels

Update attributes.adoc - fragment identifier

---

lib/asciidoctor/parser.rb
test/lists_test.rb

- automatically add bibliography style to first unordered list in bibliography section

resolves #1924 automatically add bibliography style to unordered list

---

lib/asciidoctor/parser.rb
lib/asciidoctor/section.rb

- make generate_id method on Section a static method
- delegate generate_id instance method to static method
- optimize implementation of generate_id
- use static method in parser

resolves #1929 make generate_id method on section a static method

---

lib/asciidoctor.rb
lib/asciidoctor/cli/invoker.rb
test/document_test.rb

- close files which are opened internally (and in tests)
- use dedicated path for processing STDIN in CLI invoker
- consolidate ::File.open block when writing stylesheet

resolves #1897 close all files opened internally

---

lib/asciidoctor/document.rb
test/attributes_test.rb

- if document is nested, delegate to parent to handle counter
- optimize the logic in the counter method

resolves #1942 share counters between AsciiDoc table cells and main document

---

Gemfile
asciidoctor.gemspec

Why test against old Slim if there is newer version ...

Upgrade to Slim 3

---

lib/asciidoctor.rb
test/invoker_test.rb

- validate that output file will not overwrite input file
- document the logic paths for resolving the outfile more clearly

resolves #1956 validate that output file will not overwrite input file

---

lib/asciidoctor/parser.rb
test/extensions_test.rb

- pass cloaked context as cloaked-context attribute to process method of custom block extension

resolves #1606 pass cloaked context to block extension

---

.travis.yml
Gemfile
asciidoctor.gemspec

- upgrade cucumber and JRuby to fix incompatibility

upgrade cucumber and JRuby in CI build

---

lib/asciidoctor/substitutors.rb

Works better for PHP language.

Run pygments with startinline = true

---

lib/asciidoctor/substitutors.rb

- don't drop last line of source block if line is empty aside from a callout number
- don't invoke Pygments with nowrap option as it drops trailing space
- move callout on blank last line inside table when using Pygments with table-based line numbers
- promote regexps used for post-processing Pygments output to constants

resolves #2043 don't drop last line if empty aside from callout number

---

lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb

- define method based on capabilities of Ruby
- use include? to detect presence of characters to replace before calling
- update documentation for method
- rename constants to fit the Asciidoctor code style

accelerate Substitutors#sub_specialchars method

---

README-jp.adoc

fix Japanese

---

lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb
test/extensions_test.rb

- apply default_attrs to custom inline macro
- only apply default if key is missing from attributes
- update inline macro test to verify new behavior

apply default_attrs to custom inline macro

---

lib/asciidoctor.rb
lib/asciidoctor/parser.rb
test/blocks_test.rb

- don't attempt to match block macros on indented lines
- move condition to while block
- be smarter about matching lines
- use fixed string for fallback ordered list style
- remove dead code

don't attempt to match block macros on indented lines

---

lib/asciidoctor/document.rb
test/document_test.rb

- handles case of when converter cannot be resolved during the parse phase
- use eager check for converter instance

resolves #2161 fail with informative message if converter cannot be resolved

---

lib/asciidoctor/converter/html5.rb
test/links_test.rb
test/substitutions_test.rb

add rel="noopener" to links that target _blank or when noopener option is set

resolves #2071 add rel="noopener" to links that target _blank

---

data/stylesheets/asciidoctor-default.css

- CSS for table grid should not interfere with nested tables

resolves #2151 don't allow table borders to cascade to nested tables

---

lib/asciidoctor/abstract_block.rb
lib/asciidoctor/section.rb
test/blocks_test.rb

- pull number property up from Section to AbstractNode
- store number for block when assigning caption
- consolidate logic in assign_caption method

resolves #2208 store number for formal block on node

---

lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/converter/manpage.rb
lib/asciidoctor/table.rb

- add method to retrieve rows by section

add by_section method to Table::Rows

---

lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

- fix strategy used to split the keys
- add more tests to validate the parsing

fix parsing of keys in kbd macro

---

lib/asciidoctor.rb
lib/asciidoctor/parser.rb
test/sections_test.rb

- simplify regexp for matching inline section anchor
- add test for parsing inline section anchor in setext section titles

simplify regexp for matching inline section anchor

---

lib/asciidoctor/abstract_node.rb

- only check if self is document when necessary
- change formatting
- rename default_value arg to default_val
- rename expect arg to expect_val

optimize attr and attr? methods

---

lib/asciidoctor/document.rb
lib/asciidoctor/parser.rb
test/parser_test.rb

- refactor and optimize Parser.store_attribute method
- add tests for Parser.store_attribute method
- change return value of Document#set_attribute to resolved value
- add return value to update backend/doctype methods on Document

refactor Parser.store_attribute and related methods; add tests

---

lib/asciidoctor.rb
lib/asciidoctor/document.rb
lib/asciidoctor/helpers.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/path_resolver.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/substitutors.rb

* use sloppy slice to grab end of string
* use slice method instead of []
* use slice with rindex to get file extension in some cases

optimize use of slice

---

lib/asciidoctor/parser.rb
lib/asciidoctor/table.rb
test/tables_test.rb

- use loop for cells in line; break to leave
- coerce line to nil if empty
- cache table format

optimize table parsing

---

lib/asciidoctor/substitutors.rb

- don't check for mailto: unless macroish is detected
- use local variables for detection results where possible
- update coding style

optimize macro detection

---

lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb

- non-greedy flag not needed if negated char is followed by char

remove redundant non-greedy flags in regular expressions

---

data/stylesheets/asciidoctor-default.css

- none means hide the bullet / number, but preserve indentation
- no-bullet or unnumbered (olist only) means hide the bullet / number and remove only list item indentation
- unstyled means hide the bullet / number and remove all indentation
- allow none and no-bullet to be used on ulist or olist

fix the no bullet list styles

---

lib/asciidoctor.rb
lib/asciidoctor/abstract_block.rb
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/block.rb
lib/asciidoctor/converter.rb
lib/asciidoctor/converter/docbook45.rb
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/document.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/substitutors.rb
lib/asciidoctor/table.rb
test/extensions_test.rb
test/reader_test.rb
test/test_helper.rb

rename EOL constant to LF

---

lib/asciidoctor/document.rb
test/document_test.rb

- substitute attributes line-by-line instead of as a continuous string
- test that line with missing attribute is dropped when attribute-missing is drop-line

fix default docinfo substitution behavior

---

lib/asciidoctor/reader.rb

- rename inc_lines to inc_linenos to be consistent with inc_lineno
- rename selected_lines to inc_lines
- use inc_ as variable prefix instead of include_

do some variable cleanup in reader.rb

---

lib/asciidoctor/cli/options.rb
man/asciidoctor.1
man/asciidoctor.adoc
test/options_test.rb

- add topic argument to -h flag of CLI
- dump man page when help topic is manpage
- update usage and man page to reflect new capability of -h flag
- regenerate man page
- add tests

resolves #2302 dump man page when help topic is manpage

---

lib/asciidoctor/extensions.rb
test/extensions_test.rb

- set up section in the same way the parser does
- set sectname
- set numbered
- set special
- use default level based on parent
- add rdoc
- add tests

enhance create_section helper in extensions to set up section properly

---

lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb

* Short circuit sub_replacements
* Short circuit sub_quotes
This drastically reduces the number of regular expressions that are evaluated on the text.

Short circuit subs when no match is possible

---

lib/asciidoctor/parser.rb

- remove unnecessary while loop
- remove obsolete nil checks
- consolidate variable assignments
- fix API doc

clean up Parser#next_block

---

.travis.yml
Gemfile

- update to latest versions
- use more specific version numbers for better control

update Ruby versions in CI environment

---

lib/asciidoctor/converter/docbook5.rb
test/substitutions_test.rb

resolves #2272 use the quote element in DocBook converter

---

lib/asciidoctor/document.rb
test/document_test.rb

- add callouts as key to document catalog
- add callouts method that resolves to this location

move callouts into document catalog

---

lib/asciidoctor/helpers.rb

- suppress error if directory already exists

resolves #2457 fix race condition in Helpers.mkdir_p

---

lib/asciidoctor/extensions.rb

- force core to load if extensions are loaded first

require core if not loaded when requiring extensions

---

data/stylesheets/asciidoctor-default.css

- don't let colist styles override styles for source highlighter

resolves #2474 fix CSS for highlighted source block inside colist

---

README-jp.adoc

The correct command name is 'asciidoctor', not 'asciidoctorjs'.

fixed wrong command name.

---

data/stylesheets/asciidoctor-default.css

- solves validation error without affecting behavior

resolves #2531 move @page outside of @media print in default stylesheet

---

lib/asciidoctor/converter/manpage.rb
lib/asciidoctor/table.rb
test/tables_test.rb

- see http://w3c.github.io/html/single-page.html#elementdef-tfoot

resolves #2556 output table footer after body rows

---

lib/asciidoctor.rb
lib/asciidoctor/document.rb
lib/asciidoctor/timings.rb
test/api_test.rb

- store timings object on Document
- record timing for convert in Document#convert
- record timing for write in Document#write

resolves #2574 record timings when calling convert and write on Document

---

lib/asciidoctor/reader.rb

- return true to simplify calls; also indicates success

change Reader#replace_next_line to return true

---

CHANGELOG.adoc
lib/asciidoctor/converter/docbook45.rb
lib/asciidoctor/converter/docbook5.rb
test/blocks_test.rb

resolves #1195 implement epigraph on quote block using a role

---

README-jp.adoc

There's been minor errors in Japanese README:
* typo
* not translated sentence

Fix minor errors in Japanese README

---

CHANGELOG.adoc
lib/asciidoctor/cli/invoker.rb
lib/asciidoctor/cli/options.rb
lib/asciidoctor/logging.rb
man/asciidoctor.1
man/asciidoctor.adoc
test/invoker_test.rb
test/options_test.rb

- add option to CLI to specify a failure level
- if this level is reached by a log message, it triggers a non-zero exit code

resolves #2003 allow failure level to be specified using CLI option

---

lib/asciidoctor/section.rb
test/sections_test.rb

- don't set number property by default
- simplify Section#sectnums logic
- consolidate assignments in Section#initialize
- update API docs for Section#initialize

Minor refactoring to Section class

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css

- remove negative margin from title
- center title
- reduce line height
- indent block by 1em
- simplify selectors

fix the styling of the abstract

---

test/substitutions_test.rb

* `(\((concealed)))`
* `\((visible))`

add tests for escaping indexterm shorthand

---

README-fr.adoc

Reviews welcomed !
Ping @oncletom 😉

Synchronize the french README with the original content

---

data/locale/attributes-sr.adoc
data/locale/attributes-sr_Latn.adoc

Update missing attributes for Serbian language.

Update sr and sr_Latn locale attributes

---

README-de.adoc

Improved translation little bit.

Slightly improved translation

---

lib/asciidoctor/parser.rb
test/manpage_test.rb

- don't look for NAME section if manname and manpurpose document attributes are defined
- skip comments before name section
- consume and pass on block metadata lines in front of NAME section
- only consume level-1 section when looking for NAME section
- fix references to magic regex variables in parser

resolves #2810 allow manname and manpurpose to be specified using attributes

---

CHANGELOG.adoc
lib/asciidoctor.rb
test/lists_test.rb

- regexps for any list item and description list item must agree

resolves #2888 don't hang on description list item that begins with ///

---

CHANGELOG.adoc
lib/asciidoctor/extensions.rb
test/extensions_test.rb

automatically assign title and caption on image block if title is set on custom block source

resolves #2926 automatically assign title and caption on image block

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/path_resolver.rb
test/fixtures/section-a.adoc
test/links_test.rb
test/paths_test.rb

- autoload pathname
- use Pathname#relative_path_from to resolve path outside base directory
- add test

resolves #2108 use Pathname to resolve relative path for file outside base directory

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/blocks_test.rb

* add support for starting line number on source block highlighting with Pygments or CodeRay

resolves #1742 add support for starting line number on source block

---

README-de.adoc
README-jp.adoc
README-zh_CN.adoc

fix GitHub upper / lower case

---

lib/asciidoctor/converter/factory.rb

When registering a custom converter with Asciidoctor.js the following warning message is printed:
> asciidoctor: WARNING: gem 'concurrent-ruby' is not installed. This gem is recommended when registering custom converters.
This warning message does not make sense in Asciidoctor.js and shouldn't be printed to avoid confusion.
Note: I've added a test case (on my local workspace) but I don't know how to simulate the absence of `concurrent-ruby` and/or to fake an `opal` Ruby engine...

Remove the warning when the runtime is Opal/JavaScript

---

CHANGELOG.adoc
lib/asciidoctor/converter/template.rb
test/converter_test.rb
test/fixtures/custom-backends/erb/html5/block_paragraph.html.erb
test/fixtures/custom-backends/erb/html5/open.html.erb

- use 0 instead of <
- augment test to verify behavior of trim mode
- remove encoding setting from ERB template

resolves #3006 fix deprecated ERB trim mode

---

Gemfile
asciidoctor.gemspec
test/lists_test.rb
test/tables_test.rb

* update development dependencies
* upgrade nokogiri on JRuby and fix assertions

update development dependencies

---

CHANGELOG.adoc
lib/asciidoctor/converter/html5.rb
test/blocks_test.rb

resolves #3014 add support for the mute option on vimeo videos

---

CHANGELOG.adoc
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb

resolves #3027
Tests will be added as part of #3016.

resolves #3027 highlight contents of source block even if source language is set

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css
lib/asciidoctor/converter/html5.rb

- don't hard code shaded color in source block so it works with different themes/styles

resolves #3020 don't hard code shaded color in source block

---

CHANGELOG.adoc
features/step_definitions.rb
lib/asciidoctor.rb
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/cli/options.rb
lib/asciidoctor/converter.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/stylesheets.rb
test/api_test.rb
test/invoker_test.rb
test/test_helper.rb

resolves #2995 use methods on File class instead of IO class

---

CHANGELOG.adoc
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/document.rb
test/blocks_test.rb

resolves #2953 allow icontype to be set using icons attribute

---

lib/asciidoctor/converter.rb
test/converter_test.rb

- map to DefaultFactoryProxy constructor by default
- map to CustomProxy constructor if proxy keyword arg is false

correctly map Converter::Factory.new

---

CHANGELOG.adoc
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/converter/manpage.rb
lib/asciidoctor/substitutors.rb
lib/asciidoctor/syntax_highlighter/prettify.rb
test/attributes_test.rb

resolves #3059
- change default value of fallback attribute name on attr/attr? to nil
- look for table-frame, table-grid, and table-stripes attributes on document as fallback fro frame, grid, and stripes on table

resolves #3059 change default value of fallback attribute name on attr/attr? to nil

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/blocks_test.rb
test/sections_test.rb

resolves #1173 apply substitutions to block and section titles in normal order

---

CHANGELOG.adoc
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/converter/html5.rb
test/extensions_test.rb
test/lists_test.rb

resolves #2840 transmit id and role assigned to list item in AST to output

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/reader.rb
test/api_test.rb

resolves #2884 add clearer exception message when input data is binary or has invalid encoding

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/document_test.rb
test/substitutions_test.rb

resolves #3114 log warning if footnoteref macro is found and compat mode is not enabled

---

CHANGELOG.adoc
lib/asciidoctor/converter.rb
lib/asciidoctor/document.rb
test/converter_test.rb

resolves #891 allow backend to delegate to a registered backend using the syntax synthetic:delegate

---

CHANGELOG.adoc
lib/asciidoctor/abstract_block.rb
test/api_test.rb

resolves #3101 find_by looks inside AsciiDoc table cells if traverse_documents selector is true

---

lib/asciidoctor/syntax_highlighter/coderay.rb
test/syntax_highlighter_test.rb

resolves #3137 fallback to text scanner when highlighting with CodeRay if source lang is invalid

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

resolves #2912 propogate ID assigned to inline passthrough

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/cli/options.rb
lib/asciidoctor/document.rb
lib/asciidoctor/table.rb
test/api_test.rb
test/attributes_test.rb
test/blocks_test.rb
test/converter_test.rb
test/document_test.rb
test/extensions_test.rb
test/invoker_test.rb
test/links_test.rb
test/lists_test.rb
test/manpage_test.rb
test/options_test.rb
test/reader_test.rb
test/sections_test.rb
test/substitutions_test.rb
test/tables_test.rb
test/test_helper.rb
test/text_test.rb

* still honor header_footer option as fallback for backwards compatibility

resolves #1444 rename header_footer option to standalone

---

data/locale/attributes-fr.adoc

add translation for chapter-label value

Chapter translation

---

data/locale/attributes-de.adoc

Added missing German translations

---

CHANGELOG.adoc
lib/asciidoctor/attribute_list.rb
lib/asciidoctor/extensions.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb

- rename low-level extension option
- rename local variables and argument names

rename pos_attrs to positional_attrs

---

CHANGELOG.adoc
lib/asciidoctor/converter/html5.rb

- use an AsciiMath postfilter hook to change the display property to block

resolves #2498 configure asciimath block to render as displaymath

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

resolves #3216 fix crash when attrlist is used on literal monospace phrase

---

CHANGELOG.adoc
lib/asciidoctor/syntax_highlighter/rouge.rb
test/syntax_highlighter_test.rb

resolves #3223 should not crash when source highlighter is rouge and source language is not set on block

---

CHANGELOG.adoc
lib/asciidoctor/helpers.rb
lib/asciidoctor/path_resolver.rb

- use module_function to define methods in Helpers
- move internal Helpers.uri_prefix method to PathResolver; repurpose implementation

use module_function to define methods in Helpers

---

CHANGELOG.adoc
lib/asciidoctor/rx.rb
test/substitutions_test.rb

* allow use of any word character in Unicode

resolves #3269 don't limit footnote ref to ASCII charset

---

CHANGELOG.adoc
lib/asciidoctor/rx.rb
test/substitutions_test.rb

resolves #3279 process multiple single-item menu macros in single line

---

README-jp.adoc

Updated the Japanese README to make the content the same as the latest English version line by line.

Synchronize Japanese README with English version (PR #3301)

---

data/locale/attributes-nl.adoc

Add Hoofdstuk for chapter-label

Add small translation in attributes-nl.adoc

---

data/stylesheets/asciidoctor-default.css

- add bottom margin to AsciiDoc table cell container
- use last child to revert bottom margin on AsciiDoc table cell container

resolves #3370 fix bottom margin collapsing on AsciiDoc table cell

---

.travis.yml
Gemfile
test/api_test.rb
test/invoker_test.rb

upgrade truffleruby to 19.2.0

---

test/invoker_test.rb
test/test_helper.rb

- switch to array-based arguments to prevent the command from being modified
- disable the RUBYOPT environment variable unless the use_bundler option is enabled

disable bundler in the pure CLI tests

---

CONTRIBUTING.adoc

Just a quick one I ran into when following these instructions on Ubuntu 18.04.

Add note about Nokogiri dependencies

---

.travis.yml
CHANGELOG.adoc
test/sections_test.rb

Removed a workaround in the process :wink:

Upgrade TruffleRuby to 20.0.0

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/syntax_highlighter_test.rb

resolves #3519 compute highlight line ranges on source block relative to value of start attribute

---

CHANGELOG.adoc
lib/asciidoctor/parser.rb
test/blocks_test.rb

resolves #3639 prevent collapsible block from incrementing example number

---

lib/asciidoctor/attribute_list.rb

- use lazy assignments
- group / consolidate conditional logic
- update comments; provide more examples
- remove unnecessary assignments
- format code

refactor attrlist parser

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css

- reenable again for admonition content and AsciiDoc table cells

resolves #3833 reset word wrap behavior to normal on tables

---

test/invoker_test.rb
test/paths_test.rb
test/reader_test.rb
test/substitutions_test.rb
test/syntax_highlighter_test.rb
test/test_helper.rb

- also define windows? as static method for these cases

add if and unless conditions to tests to make filtering more readable

---

test/reader_test.rb

I've been using rootless containers with podman
and I end up running the tests as root.

feat: enable running tests as root

---

docs/antora.yml
docs/modules/ROOT/pages/features.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/api/pages/index.adoc
docs/modules/install/pages/index.adoc

- remove attribute entry in component descriptor for URL

update AsciidoctorJ URLs to xrefs and page ID

---

docs/modules/api/pages/options.adoc

Document the header_only option

---

CHANGELOG.adoc
lib/asciidoctor/document.rb
test/attributes_test.rb

resolves #3939 counter should not override locked attributes

---

lib/asciidoctor/converter/semantic-html5.rb
test/fixtures/semantic-html5-scenarios/author-with-email.adoc
test/fixtures/semantic-html5-scenarios/author-with-email.html
test/fixtures/semantic-html5-scenarios/author.adoc
test/fixtures/semantic-html5-scenarios/author.html
test/fixtures/semantic-html5-scenarios/authors-with-email.adoc
test/fixtures/semantic-html5-scenarios/authors-with-email.html
test/fixtures/semantic-html5-scenarios/authors.adoc
test/fixtures/semantic-html5-scenarios/authors.html

This is the first part of #3967 where we generate semantic constructs for the author(s).

ref #3967 generate author(s)

---

lib/asciidoctor/converter/semantic-html5.rb
test/fixtures/semantic-html5-scenarios/revision-with-date-MMMM-dd-yyyy.adoc
test/fixtures/semantic-html5-scenarios/revision-with-date-MMMM-dd-yyyy.html
test/fixtures/semantic-html5-scenarios/revision-with-date-MMMM-dd.adoc
test/fixtures/semantic-html5-scenarios/revision-with-date-MMMM-dd.html
test/fixtures/semantic-html5-scenarios/revision-with-date-invalid-format.adoc
test/fixtures/semantic-html5-scenarios/revision-with-date-invalid-format.html
test/fixtures/semantic-html5-scenarios/revision-with-date-version-remark.adoc
test/fixtures/semantic-html5-scenarios/revision-with-date-version-remark.html
test/fixtures/semantic-html5-scenarios/revision-with-date-version.adoc
test/fixtures/semantic-html5-scenarios/revision-with-date-version.html
test/fixtures/semantic-html5-scenarios/revision-with-date.adoc
test/fixtures/semantic-html5-scenarios/revision-with-date.html
test/fixtures/semantic-html5-scenarios/revision-with-remark.adoc
test/fixtures/semantic-html5-scenarios/revision-with-remark.html
test/fixtures/semantic-html5-scenarios/revision-with-version-remark.adoc
test/fixtures/semantic-html5-scenarios/revision-with-version-remark.html
test/fixtures/semantic-html5-scenarios/revision-with-version-without-label.adoc
test/fixtures/semantic-html5-scenarios/revision-with-version-without-label.html
test/fixtures/semantic-html5-scenarios/revision-with-version.adoc
test/fixtures/semantic-html5-scenarios/revision-with-version.html

This is the second part of #3967 where we generate revision.

ref #3967 generate revision

---

lib/asciidoctor/reader.rb

Give this refactoring a chance to run through CI.

rewrite Reader#read_lines_until

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css
lib/asciidoctor/rouge_ext.rb
lib/asciidoctor/syntax_highlighter/rouge.rb
src/stylesheets/asciidoctor.css
test/syntax_highlighter_test.rb

resolves #3641 add support for inline linenums mode when using Rouge as source highlighter

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css
data/stylesheets/coderay-asciidoctor.css
src/stylesheets/asciidoctor.css
src/stylesheets/coderay-asciidoctor.css

resolves #4128 prevent line numbers on source block in HTML output from being selected

---

CHANGELOG.adoc
lib/asciidoctor/converter/html5.rb
test/api_test.rb

Fixes #4143.
The test seems to pass and appears to be right to me, but this was my first Asciidoctor test.

resolves #4143 omit meta generator tag if reproducible document attribute is set

---

docs/modules/tooling/pages/index.adoc

Add link to Asciidoctor.js Live Preview for MS-Edge browser

Update web browser add-ons section

---

README-fr.adoc
README-zh_CN.adoc

According to the discussions in #4280 and add the German document reference link in other docs.

Add German document link and clarify the names

---

README-zh_CN.adoc

Rebuild the zh readme doc

---

devdocs/modern-html-converter/built-in-roles.adoc
lib/asciidoctor/converter/semantic_html5.rb
test/fixtures/semantic-html5-scenarios/bold-text.adoc
test/fixtures/semantic-html5-scenarios/bold-text.html
test/fixtures/semantic-html5-scenarios/double-quoted-text.adoc
test/fixtures/semantic-html5-scenarios/double-quoted-text.html
test/fixtures/semantic-html5-scenarios/italic-text.adoc
test/fixtures/semantic-html5-scenarios/italic-text.html
test/fixtures/semantic-html5-scenarios/mark-text.adoc
test/fixtures/semantic-html5-scenarios/mark-text.html
test/fixtures/semantic-html5-scenarios/monospace-text.adoc
test/fixtures/semantic-html5-scenarios/monospace-text.html
test/fixtures/semantic-html5-scenarios/single-quoted-text.adoc
test/fixtures/semantic-html5-scenarios/single-quoted-text.html
test/fixtures/semantic-html5-scenarios/subscript-text.adoc
test/fixtures/semantic-html5-scenarios/subscript-text.html
test/fixtures/semantic-html5-scenarios/superscript-text.adoc
test/fixtures/semantic-html5-scenarios/superscript-text.html
test/fixtures/semantic-html5-scenarios/underlined-text.adoc
test/fixtures/semantic-html5-scenarios/underlined-text.html

bold, italiic, quotes, superscripts, etc

html-converter-next inline_quotes

---

lib/asciidoctor/converter/semantic_html5.rb
test/fixtures/semantic-html5-scenarios/listing-with-caption.adoc
test/fixtures/semantic-html5-scenarios/listing-with-caption.html
test/fixtures/semantic-html5-scenarios/listing-with-id-roles.adoc
test/fixtures/semantic-html5-scenarios/listing-with-id-roles.html
test/fixtures/semantic-html5-scenarios/listing-with-nowrap.adoc
test/fixtures/semantic-html5-scenarios/listing-with-nowrap.html
test/fixtures/semantic-html5-scenarios/listing-with-title.adoc
test/fixtures/semantic-html5-scenarios/listing-with-title.html
test/fixtures/semantic-html5-scenarios/listing.adoc
test/fixtures/semantic-html5-scenarios/listing.html
test/fixtures/semantic-html5-scenarios/source-with-lang-title.adoc
test/fixtures/semantic-html5-scenarios/source-with-lang-title.html

resolves #4071 use semantic constructs for listing blocks

---

lib/asciidoctor/converter/semantic_html5.rb
test/fixtures/semantic-html5-scenarios/hard-break-document.adoc
test/fixtures/semantic-html5-scenarios/hard-break-document.html
test/fixtures/semantic-html5-scenarios/hard-break-individual.adoc
test/fixtures/semantic-html5-scenarios/hard-break-individual.html
test/fixtures/semantic-html5-scenarios/hard-break-paragraph.adoc
test/fixtures/semantic-html5-scenarios/hard-break-paragraph.html

add convert thematic break method to the semantic HTML 5 converter

---

devdocs/modern-html-converter/built-in-roles.adoc
lib/asciidoctor/converter/semantic_html5.rb
test/fixtures/semantic-html5-scenarios/button-text.adoc
test/fixtures/semantic-html5-scenarios/button-text.html

add convert button method in the semantic HTML 5 converter

---

docs/modules/ROOT/pages/safe-modes.adoc

The alternative would be to simple delete "since" and leave two separate sentences.

Fix sentence structure

---

data/locale/attributes-sl.adoc

Hello, this adds Slovenian (sl_SI) locale. Thank you.

Add Slovenian locale

---

docs/modules/extensions/pages/index.adoc
docs/modules/extensions/pages/preprocessor.adoc
docs/modules/extensions/pages/tree-processor.adoc

And add links to the API documentation.

Explain Preprocessor and TreeProcessor

---

docs/modules/convert/pages/contexts-ref.adoc

Fixed a typo in contexts-ref.adoc

---

data/locale/attributes-sw.adoc

Possible error in Tuki dictionary
https://github.com/asciidoctor/asciidoctor/pull/4454

Use common term

---

docs/modules/migrate/pages/ms-word.adoc

This pull request addresses the deprecation of the "asciidoctor" command in the options by updating it to the recommended "asciidoc" command for better compatibility and adherence to current best practices.

 Update the pandoc command in the options from the deprecated "asciidoctor" to "asciidoc."
