lib/asciidoctor/timings.rb
test/document_test.rb

- coerce values to float, not integer
- add tests for precision and handling nil values

resolves #1342 fix precision error in timings report

---

bin/asciidoctor

Allow to require asciidoctor when then `lib/` directory is not relative to the binary.
For instance, Debian package copies binary in `/usr/bin/asciidoctor` and lib/ in `/usr/lib/ruby/vendor_ruby/`

Fallback to require with a non relative path

---

lib/asciidoctor/parser.rb
test/lists_test.rb

- use begin...while loop to work around bug in Opal
- add test for definition list when more than 4 consecutive colons are used

resolves #1408 use while loop instead of begin...while loop

---

lib/asciidoctor/abstract_node.rb
lib/asciidoctor/helpers.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/stylesheets.rb
lib/asciidoctor/substitutors.rb

- don't abort if server-side syntax highlighter isn't available (coderay, pygments)
- only attempt to load source highlighting library if not already loaded
- use document attribute to avoid redundant warnings if library can't be loaded
- use basic substitutions (specialcharacters, callouts) if source highlighter isn't available
- don't abort trying to load the Pygments stylesheet if Pygments isn't available
- add on_failure argument to require_library helper to control behavior on load failure

resolves #1253 don't abort of syntax highlighter isn't available

---

data/stylesheets/asciidoctor-default.css
data/stylesheets/coderay-asciidoctor.css
lib/asciidoctor/substitutors.rb

- use highlight attribute on source block to specify lines to be highlighted
- add method to resolve the highlight lines spec
- disable bold_every option in CodeRay
- darken bolded line numbers in default CodeRay theme
- set line height of table cells used for syntax highlighting
- fix invalid color value in default CodeRay theme

resolves #1429 allow text of selected lines to be highlighted in source block

---

asciidoctor.gemspec

Ref: http://www.rubydoc.info/github/rubygems/rubygems/Gem%2FSpecification%3Arubyforge_project

remove deprecated rubyforge_project option

---

lib/asciidoctor.rb
lib/asciidoctor/document.rb

- assign outfilesuffix to instance variable on Document after parsing header
- expose reader for outfilesuffix property on Document
- force load method to parse document when invoked from convert* methods

resolves #1412 use outfilesuffix defined in header when resolving outfile

---

lib/asciidoctor/opal_ext/file.rb

See https://github.com/asciidoctor/asciidoctor-extensions-lab/pull/32#issuecomment-98092816
Absolute paths starting with `file://` were considered as relative path (in safe mode) and an exception was thrown:
```
SecurityError : asciidoctor: FAILED: : Failed to parse source, Jail is not an absolute path: file:///workspace/asciidoctor-extensions-lab/lib/chart-block-macro
```
In unsafe mode, the method `read_asset` was using `IO.read` (with no equivalent when running in Opal). AFAIK `::IO.read` and `::File.read` are equivalent so I replaced the first one with the latter.
Finally the method `readable` was undefined when running in Opal so I added the method in `opal_ext/file.rb`. I didn't know how to implement the method in a JavaScript environment so for now the method always returns `true` …

Allow to read assets when running in Opal

---

lib/asciidoctor/abstract_node.rb
test/attributes_test.rb

This PR adds a method `AbstractNode#add_role` to add a role to a certain node.
Document level roles are not considered when adding a role, it will be added in any case, if the node itself does not carry that role yet.

Fixes #1366: Added method AbstractNode#add_role

---

asciidoctor.gemspec
lib/asciidoctor/converter/docbook5.rb
test/blocks_test.rb

Add an Asciimath parser and MathML generator. This enables conversion of asciimath expressions to MathML in the docbook5 converter.

Add asciimath support for docbook5

---

lib/asciidoctor/document.rb
test/paragraphs_test.rb
test/test_helper.rb

- don't fail if output is nil
- don't output trailing endline if output is empty
- inline doctype should return nil if there's nothing to convert

resolves #1544 built-in writer should not fail if output is nil

---

data/stylesheets/asciidoctor-default.css
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/converter/html5.rb
test/blocks_test.rb
test/fixtures/circle.svg
test/substitutions_test.rb

- use object element to embed SVG in HTML if interactive option is set 
- embed SVG data directly if inline option is set (including remote URI)
- always use img element for SVG if safe mode is secure
- add CSS to make object element with image/svg+xml data behave like img element
- add tests for SVG images
- consolidate/cleanup code in converter

resolves #1301 and #1224 add support for interactive & inline SVGs

---

lib/asciidoctor/converter/manpage.rb

Resolves #1590: Generated .URL call should be followed by a \c so no extraneous space is introduced.

Fix for #1590

---

lib/asciidoctor/converter/template.rb

Setting instance attributes of the Template class cannot depend on
whether slim has been loaded before or not.

Initialize slim-related attributes regardless of when slim was loaded

---

lib/asciidoctor/converter/manpage.rb

Fix for #1589. Line beginning with `\.` should be translated as `\&.`, so as not to be mistaken for a troff macro call.

Fix for #1589

---

lib/asciidoctor/converter/docbook5.rb
test/document_test.rb
test/links_test.rb

- change xlink namespace to xl to prevent invalid substitutions
- add test for square brackets in link text

resolves #1597 change xlink namespace to xl in DocBook 5 output

---

lib/asciidoctor/converter/docbook5.rb
test/blocks_test.rb
test/substitutions_test.rb

- convert inline asciimath to MathML when asciimath gem is available
- wrap asciimath source in mathphrase element when asciimath gem is not available
- wrap latexmath source in mathphrse element
- only use alt element for latexmath

resolves #1622 convert inline asciimath to MathML in DocBook converter

---

lib/asciidoctor/converter/html5.rb
test/tables_test.rb

- prevent default toc from being inserted into AsciiDoc table cell
- add test to cover scenario

resolves #1582 don't include default toc in nested document

---

lib/asciidoctor/converter/html5.rb
lib/asciidoctor/document.rb
test/tables_test.rb

- don't pass toc location attributes (toc, toc-placement, toc-position) to subdocument
- allow toc to be enabled in AsciiDoc table cell
- add tests for more toc scenarios in AsciiDoc table cell

reresolves #1582 don't pass toc location attributes to subdocument

---

lib/asciidoctor/converter/manpage.rb
test/manpage_test.rb

- remove redundant backslashes
- only put backslash in front of backslash & single quote in single-quoted strings
- substitute non-breaking space character in manify
- fix colist formatting
- add test for colist
- add apidoc for manify method arguments

refinements to manpage converter

---

lib/asciidoctor.rb
test/lists_test.rb

- fix false positive when checking for start of list causing an infinite loop
- optimize the AnyListRx regex (only check up to blank as we know non-blank follows)

resolves #1679 fix false positive for start of list

---

data/locale/attributes.adoc

I've changed my mind.
If the "Chapter" string is present "by default" it is just right to translate it. If I do not want it, it is easy to un-assign the string for all languages altogether.

Updated Italian translation

---

lib/asciidoctor/section.rb
test/sections_test.rb

- short-circuit prefix check if idseparator is blank
- add test for when idprefix and idseparator are both blank
- add test to verify leading idseparator is dropped if idprefix is empty

fix crash in generate_id when both idprefix & idseparator are blank

---

lib/asciidoctor/extensions.rb
test/extensions_test.rb

- dup attributes before passing to next_block
- return parent node from parse_content method
- use === for type comparison instead of is_a?

resolves #1651 don't share attributes between blocks parsed by parse_content

---

lib/asciidoctor/parser.rb
lib/asciidoctor/table.rb
test/tables_test.rb

- don't check for implicit header if noheader option is set
- don't check for implicit header if header option is set (already implied)

resolves #1849 only disable implicit header on table when noheader option is set

---

lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/table.rb
test/tables_test.rb

- add orient="land" attribute to tables if orientation attribute or landscape option is specified

resolves #1815 add support for orient="land" on tables in DocBook

---

data/stylesheets/asciidoctor-default.css

- enable font smoothing in the default stylesheet for Firefox (OSX) using the -moz-osx-font-smoothing property
- consolidate styles for body element

resolves #1837 enable font smoothing in default stylesheet for Firefox (OSX)

---

lib/asciidoctor/converter/html5.rb

- allow sectanchors & sectlinks to be used in tandem in the HTML5 converter

resolves #1806 allow sectanchors & sectlinks to be used in tandem

---

data/stylesheets/asciidoctor-default.css

- use CSS to forcefully break monospace phrase if it exceeds length of line
- introduce nobreak role on monospace phrase to restore old behavior (break only at break opportunity)
- introduce nowrap role on monospace phrase to prevent line breaks

resolves #1814 forcefully break monospace phrase if it exceeds length of line

---

lib/asciidoctor/path_resolver.rb

* `file://c:/foo/bar` is absolute (Windows path)
* `file:///foo/bar` is absolute (Linux path)
* `file://host/foo/bar` is absolute (URI path)
Currently `is_root?` method will return false when the path is `file://c:/foo/bar` (absolute path on Windows)

Paths with file URI scheme are inevitably absolute

---

lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/parser.rb
test/blocks_test.rb

- treat scaledwidth, scale and width attributes on a block image as mutually exclusive
- update tests
- optimize how % is added to a unitless scaledwidth value

resolves #1059 respect image scaling in DocBook converter

---

lib/asciidoctor/converter/docbook5.rb
test/document_test.rb

- support front-cover-image and back-cover-image
- value can be a raw path or an image macro

resolves #1939 add support for book covers in DocBook 5 converter

---

asciidoctor.gemspec

Some of test files were missing (test_helper.rb and fixtures folder). This PR included them into the gem, although it is not as careful about included files as the other RegExps ...
Other option would be to drop the test suite from the gem entirely ...

Include entire test suite in gem

---

lib/asciidoctor.rb
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/path_resolver.rb
test/blocks_test.rb
test/paths_test.rb

- allow spaces in target of block image
- URL encode spaces in web paths, including image URIs (replace space with %20)

resolves #1943 allow spaces in target of block image

---

lib/asciidoctor/abstract_node.rb
lib/asciidoctor/document.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb
test/attributes_test.rb

- use empty string as default value for set_attr and set_attribute methods
- use set_attr to assign compat-mode and title-separator attributes on document

resolves #1967 use empty string as default value for set_attr method

---

lib/asciidoctor/converter/manpage.rb
test/manpage_test.rb

* escape the roff line break command
* unescape escaped roff commands after the leading period substitution pass

preserve inline break in manpages

---

lib/asciidoctor/converter/manpage.rb
test/manpage_test.rb

When using inline styling in a manpage table cell, the resulting manpage would result in `<BOUNDARY>` tags in the output. Call the manify function to fix up the text and remove these tags.

Avoid boundary pseudo-tags in manpage table output

---

lib/asciidoctor/block.rb
lib/asciidoctor/core_ext.rb
lib/asciidoctor/core_ext/1.8.7/symbol/empty.rb
lib/asciidoctor/core_ext/1.8.7/symbol/length.rb
lib/asciidoctor/document.rb
lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

- short-circuit apply_subs if source or subs arguments are empty
- only check for empty subs again in apply_subs after resolving substitution aliases
- fix tomdoc on apply_subs method
- change docinfosubs assignment so it isn't resolved multiple times
- don't check for subs key on passthrough entry as it's required
- consolidate code
- add tomdoc to the Document#resolve_docinfo_subs method

optimize the Substitutors#apply_subs method

---

lib/asciidoctor.rb
lib/asciidoctor/helpers.rb

* use unpack('C3') to grab leading bytes
* define BOM chars using 0x shorthand
* use optimized version of slice to reduce bytes array
* don't slice leading bytes array when checking for UTF-8 BOM

improve BOM processing

---

lib/asciidoctor.rb
lib/asciidoctor/document.rb
test/manpage_test.rb

- set filetype to man when backend is manpage
- add test to verify manpage-related attributes are set in manpage backend
- add manpage to list of default extensions map

resolves #2055 set filetype to man when backend is manpage

---

lib/asciidoctor/table.rb
test/tables_test.rb

- address edge cases where escaped quotes were misinterpreted as enclosing quotes
- add edge cases to test

resolves #2008 don't confuse escaped quotes in CSV data as enclosing quotes

---

lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

- fix stray marks added when unescaping unconstrained (double plus) passthroughs
- add tests

fix stray marks added when unescaping unconstrained passthroughs

---

lib/asciidoctor.rb
test/sections_test.rb

- match either all equals (=) or all hashes (#), not a mix of both

resolves #2074 don't match headings with mixed leading characters

---

lib/asciidoctor.rb
lib/asciidoctor/parser.rb

- don't match trailing > for arabic list type
- remove unnecessary assignment
- use chop instead of chomp to remove trailing char
- update comments

optimize list marker resolution

---

lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb

- consistently disallow leading tab and add note
- promote + to constant in substitutors
- use slice instead of chomp to remove trailing line break
- check for trailing line break before attempting to remove
- formatting

optimize line break substitution

---

lib/asciidoctor/path_resolver.rb
lib/asciidoctor/reader.rb

This special case is unnecessary (or at least not necessary anymore on Node).
Should fix this issue: https://github.com/asciidoctor/atom-asciidoc-preview/issues/189

Use a special logic for include processing only on a browser environment

---

lib/asciidoctor/parser.rb
test/parser_test.rb

- when reparsing overrides; reconstruct compound names if necessary
- add test for multiple authors with compound names

resolves #663 don't mangle compound names when document has multiple authors

---

lib/asciidoctor.rb
test/links_test.rb
test/test_helper.rb

- don't skip sequential inline anchor macros
- make inline anchor macro less greedy; only match valid id chars

resolves #1689 fix sequential inline anchor macros with empty reftext

---

lib/asciidoctor.rb
test/extensions_test.rb

Avoids the need for the `require 'asciidoctor/extensions'` statement.

autoload extensions source file when Asciidoctor::Extensions is referenced

---

lib/asciidoctor/extensions.rb
lib/asciidoctor/substitutors.rb
test/extensions_test.rb

- resolve attributes for short inline macros if content model is attributes
- don't attempt to parse an empty attribute string
- use text between square brackets as fallback value for target for backwards compat
- overlay parsed attributes on top of default attributes
- use abbreviated regexp delimiters
- add additional tests for various permutations of the inline macro

resolves #1797 resolve attributes for short inline macros if requested

---

Rakefile
lib/asciidoctor.rb
lib/asciidoctor/extensions.rb
test/extensions_test.rb

- validate name of inline macro
- cache inline macro rx between invocations
- remove warning in test suite
- remove unnecessary require in rake build

resolves #2136 validate name of inline macro; cache inline macro rx

---

data/locale/attributes.adoc

This adds support for Norwegian Nynorsk (language code: nn).
It also updates the Norwegian Bokmål translation, by adding a
few missing translations (chapter-label, listing-caption, preface-title)
and improving a few of the existing ones by making them more
idiomatic and consistent with other software (notable the babel
package in LaTeX).
Note that the language code for Norwegian Bokmål has been
corrected from ‘no’ to ‘nb’. There are only two written Norwegian
languages, Norwegian Bokmål (language code: nb) and
Norwegian Nynorsk (language code: nn). The older ‘no’ language
code should not be used for either of the written Norwegian
languages, only for spoken Norwegian.

Added Norwegian Nynorsk translation and updated Norwegian Bokmål translation

---

lib/asciidoctor/parser.rb
lib/asciidoctor/table.rb
test/tables_test.rb

- allow tab separator for table to be specified using \t
- recognize tsv format as alias for csv format using tab separator
- warn at error level if table format is illegal instead of throwing exception
- consolidate code to resolve regular expression for table separator
- format attribute should take precedence over implicit table separator
- add tests for tab as separator
- add test to verify format attribute takes precedence

resolves #2073 allow tab separator to be specified using \t

---

lib/asciidoctor/document.rb
lib/asciidoctor/helpers.rb
test/document_test.rb

- fail is just an alias for raise
- use a specific exception class for better flow control
- use LoadError when raising from rescued LoadError
- use NotImplementedError if converter is not set to bypass load rescue

use raise with exception class instead of fail

---

data/stylesheets/asciidoctor-default.css
lib/asciidoctor/converter/html5.rb
test/substitutions_test.rb

- allow menu caret to be styled independently by encosing in tag
- switch default caret to &#8250;
- use character from Font Awesome for caret if font-based icons are enabled

resolves #2165 enclose menu caret in tag

---

lib/asciidoctor/converter/html5.rb
lib/asciidoctor/parser.rb
test/document_test.rb
test/parser_test.rb

- sanitize content of authors meta tag in HTML output
- sanitize value of author and authors attribute before partitioning
- consolidate author metadata assignment
- add tests

resolves #2112 sanitize content of authors meta tag in HTML output

---

lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb
test/links_test.rb
test/substitutions_test.rb

- simplify match of attrlist for inline macro to \[(|.*?[^\\])\]
* trailing backslash only supported if followed by space or escaped using a passthrough
- simplify match for attrlist on block macro to \[(.*)\]
- use non-greedy matches instead of exclusion-based matches
- use multiline flag instead of exclusions to match over lines
- rename EmailInlineMacroRx to EmailInlineRx
- add more tests for backslash in attrlist
- allow content of inline pass macro to be empty

refactor regexps for macros and directives

---

lib/asciidoctor.rb
lib/asciidoctor/document.rb
lib/asciidoctor/substitutors.rb
test/attributes_test.rb
test/blocks_test.rb
test/substitutions_test.rb

- don't crash if resolve_subs resolves nil value
- make match for substitution list on pass and stem macro more strict
- use optional match group to capture subs for pass and stem macro

resolves #2183 don't crash if substitution list resolves to nil

---

lib/asciidoctor/substitutors.rb
test/links_test.rb

- make logic more clear
- use variable to track when we're processing a macro vs bare URL
- optimize logic
- don't parse link text of non-mailto link unless text starts with " or contains both , and =
- fix case of a nil pointer when attributes are parsed but there's no link text
- move registration of link after parsing logic
- add additional test cases

optimize link macro substitution and add additional tests

---

lib/asciidoctor.rb
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/converter/html5.rb

- add docfile to warning message emitted when stylesheet cannot be read
- warn when stylesheet to copy cannot be read
- allow label to be passed to read_asset method
- refer to missing file as a stylesheet

resolves #2089 include docfile in warning when stylesheet cannot be read

---

lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb
test/links_test.rb

- don't match link macro with two colons
- allow target of link macro to be empty

resolves #2202 don't match link macro with two colons

---

lib/asciidoctor.rb
lib/asciidoctor/reader.rb
test/fixtures/mismatched-end-tag.adoc
test/fixtures/tagged-class-enclosed.rb
test/fixtures/tagged-class.rb
test/reader_test.rb

- in addition to including tags, add option to exclude tags using !name syntax
- introduce wildcard for including all (\*) or excluding all (!*) tags
- introduce wildcard for selecting non-tagged lines (**)
- don't select nested tags with wildcard if ancestor tag is excluded
- warn if a mismatched or unexpected end tag is found
- improve efficiency of detecting and processing tag directives
- maintain a tag stack for handling nested tags
- skip call to push_include if selected lines array is empty
- ignore tag and tags attribute if empty (previously caused an infinite loop)
- add tests for excluding tags

resolves #1516 add option to exclude tags when including file

---

lib/asciidoctor.rb
lib/asciidoctor/attribute_list.rb
lib/asciidoctor/parser.rb
test/attributes_test.rb
test/links_test.rb

- use [ \t] (or just space) instead of \p{Blank}
- use CG_BLANK in front of bare URL
- use regexp to strip whitespace for text that follows label of admonition paragraph
- disallow tabs in certain places
- don't allow contents of block attribute list to begin with space
- optimize manpage header processing
- only match space, tab and newline when splitting attributes

resolves #2204 use [ \t] instead of \p{Blank} to match spaces

---

lib/asciidoctor.rb

- use zero-based ranges where possible

optimize regexp ranges

---

lib/asciidoctor/converter/html5.rb
lib/asciidoctor/converter/manpage.rb
lib/asciidoctor/parser.rb

- coerce level to 1 for special sections defined at level 0
- skip unnecessary level logic in parser and converter as a result

resolves #1261 set correct level for special sections in parser

---

lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb
test/links_test.rb

- don't allow double quotes around id
- don't strip double quotes around reftext
- update relevant tests

no double quotes in xref macro

---

lib/asciidoctor.rb
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb
test/links_test.rb
test/lists_test.rb
test/substitutions_test.rb

- scan for bibliography anchors in bibliography list and save in document catalog
- don't scan for or convert bibliography anchors elsewhere in the document
- don't allow a bibliography anchor to be escaped
- allow reftext to be specified for bibliography anchors
- use reftext, if specified, as label in front of bibliography entry
- use reftext, if specified, for text of xref that refers to bibliography entry
- use a dedicated rx to scan for normal inline anchors
- don't catch a bibliography when scanning for normal inline anchors
- add tests

resolves #560 and #1562 catalog bibliography anchors and capture reftext

---

lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

- check for captured leading and trailing brackets more carefully
- strip brackets that are not part of term and restore when converting text
- consolidate code to reduce redundant conditionals
- use slice with fixed positions when taking substrings

resolves #1581 prevent leading & trailing brackets from getting caught in indexterm

---

lib/asciidoctor/converter/base.rb
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/parser.rb
test/blocks_test.rb

- encode double quote characters in image alt text when used in attribute value
- defer encoding characters in alt text to converter
- process image attributes after creating image block

resolves #2061 encode double quotes in image alt text

---

lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

- don't use delimiter at start or end of keys value
- locate delimiter using index instead of regexp
- add additional tests for kbd macro

resolves #1660 be more precise about splitting kbd characters

---

lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

The warning has the following form:
asciidoctor: WARNING: could not resolve xref:
closes #2268

Adds a warning if verbose is set and xref is not found

---

lib/asciidoctor/abstract_node.rb
test/blocks_test.rb

- encode spaces in a qualified URI in addition to a relative path
- ensures image_uri and similar methods always returns path with URI encoded spaces

encode spaces in URI

---

lib/asciidoctor.rb
lib/asciidoctor/reader.rb
test/reader_test.rb

- permit target to begin or end with operator
- don't drop empty conditions as these should be considered
- only call target.empty? once
- optimize conditional stack size check
- add tests

permit leading, trailing, and repeat operators in target of preprocessor conditional

---

lib/asciidoctor/abstract_block.rb
test/blocks_test.rb

- substitute replacements in alt text of block image
- improve tests for substitutions in alt text of block image

substitute replacements in alt text of block image

---

lib/asciidoctor.rb
lib/asciidoctor/abstract_block.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb
test/blocks_test.rb

- store generated alt text in dedicated attribute
- don't apply replacements to auto-generated alt text
- add test to assert behavior

keep track of when alt text is auto-generated

---

lib/asciidoctor.rb
test/substitutions_test.rb

- don't recognize inline image macro if target has trailing space
- fix test for inline image macro with newline in target
- swap order of space and open square bracket in regexp

don't recognize inline image macro if target has trailing space

---

data/locale/attributes.adoc
features/xref.feature
lib/asciidoctor/abstract_block.rb
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/attribute_list.rb
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/document.rb
lib/asciidoctor/inline.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/section.rb
lib/asciidoctor/substitutors.rb
test/blocks_test.rb
test/document_test.rb
test/links_test.rb
test/sections_test.rb
test/substitutions_test.rb

- store referenceable nodes under refs key in document catalog
- when registering a ref, store entry in both refs table and deprecated ids table
- update tests to use consolidated register method
- add xreftext method to AbstractBlock, Section, and Inline to produce formatted text for xref
- add API docs to the xreftext methods
- format xref text according to xrefstyle attribute, if set (full, short, or basic)
- move reftext? and reftext methods down to AbstractBlock and Inline; contextualize
- apply reftext substitutions (specialchars, quotes, replacements) to value returned by reftext method
- drop support for reftext document attribute
- don't catalog inline anchor if reftext containing attribute reference resolves to empty string
- use reftext method instead of text method for :ref in …

resolves #858 add support for formal xref text

---

lib/asciidoctor/abstract_block.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/converter/manpage.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/section.rb
lib/asciidoctor/table.rb
test/blocks_test.rb

- use textlabel to store the textual label for the admonition type
- don't transfer caption attribute to caption property if block does not have a title
- route calls to caption method on admonition block to textlabel attribute
- formatting

use textlabel instead of caption to store textual label of admonition

---

lib/asciidoctor/converter/html5.rb
lib/asciidoctor/converter/manpage.rb
test/lists_test.rb

- retain block content in items of callout list when converting to HTML and man page
- update tests
- code formatting

resolves #1478 retain block content in items of callout list

---

lib/asciidoctor.rb
test/extensions_test.rb

* load extensions lazily (don't trigger premature autoload)
* add test to verify autoloading behavior

autoload extensions lazily

---

lib/asciidoctor/parser.rb
test/blocks_test.rb

- within a delimited block, continue to read blocks after content is skipped
- add missing test for scenario

continue to read blocks after skipped content within delimited block

---

lib/asciidoctor/parser.rb
lib/asciidoctor/reader.rb

- don't track eof state; recalculate on demand
- split impl of has_more_lines? and eof? between Reader and PreprocessorReader
- swap eof? and empty? alias (use empty? as primary method)

don't track eof state in reader

---

lib/asciidoctor/converter/html5.rb
test/links_test.rb

- use path without fragment as default text instead of [refid]

change default text for inter-document xref

---

lib/asciidoctor/parser.rb
test/blocks_test.rb

- drop skipped content inside of creating empty paragraphs
- add missing test for scenario

drop skipped content inside a delimited block

---

lib/asciidoctor/extensions.rb
test/extensions_test.rb

- group names of extensions are stored internally as symbols
- group name can be specified as symbol or string when registering or unregistering extension

resolves #2324 coerce group name to symbol when registering extension

---

lib/asciidoctor/parser.rb
test/extensions_test.rb

- return nil if content model is skip
- reset attributes after call to build_block if return value is nil
- add test to verify BlockProcessor#process isn't called if content model is skip

don't mix return type of Parser.build_block method

---

lib/asciidoctor.rb

- change warning to preserve legacy scenario

resolves #2323 don't warn if src stylesheet can't be read and dest exists

---

lib/asciidoctor/parser.rb
test/sections_test.rb

- preprocess second line of setext discrete heading
- use is_single_line_section_title? if setext section titles are disabled
- change "floating title" to "discrete heading" in test suite

preprocess second line of setext discrete heading

---

lib/asciidoctor/abstract_node.rb
lib/asciidoctor/path_resolver.rb
lib/asciidoctor/reader.rb
test/paths_test.rb

- return filename as relative path if filename doesn't share common root with base directory
- add test for scenario

resolves #2107 calculate relative path correctly

---

test/attributes_test.rb
test/blocks_test.rb
test/converter_test.rb
test/document_test.rb
test/extensions_test.rb
test/invoker_test.rb
test/links_test.rb
test/lists_test.rb
test/paragraphs_test.rb
test/parser_test.rb
test/reader_test.rb
test/sections_test.rb
test/substitutions_test.rb
test/tables_test.rb

- replace assert ! with refute
- use assert_nil and refute_nil
- use assert_empty and refute_empty
- use assert_kind_of instead of direct is_a? call
- use assert_respond_to instead of direct respond_to? call

use refute in place of assert ! in test suite

---

lib/asciidoctor/extensions.rb
test/extensions_test.rb

`target` and `alt` attributes are mandatory to create an image block.

Resolves #2349, check mandatory attributes when creating an image block

---

lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

- interpret escaped concealed indexterm shorthand as flow index term enclosed in round brackets

resolves #2363 allow flow indexterm to be enclosed in round brackets

---

asciidoctor.gemspec

This fixes dependencies installation on Windows with ruby >= 2.4.

update nokogiri to 1.8.0 for ruby >= 2.1

---

appveyor.yml

Added available ruby versions to the build matrix of AppVeyor builds to ensure things are going fine on Windows. I saw the comment about nokogiri issues but I wonder how things are going on now.

update rubies list in appveyor build matrix

---

lib/asciidoctor/abstract_block.rb
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/parser.rb

- automatically assign parent node in << method on block
- only use << method internally when functionality is needed

resolves #2398 automatically assign parent reference when adding node to parent

---

lib/asciidoctor.rb

This simply adds '.plist' as an extension that can contain XML-like comments (after all, Property Lists can be and usually are XML files.)

Fixes #2430

---

features/xref.feature
lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb

- add Compliance.natural_xrefs
- don't resolve xref by reference text if compat-mode is on
- don't resolve xref by reference text if compliance setting is disabled
- add test scenario
- rename scenarios related to natural xrefs

resolves #2405 add compliance setting to disable natural cross references

---

README.adoc

I added asciidoctor to Homebrew, the package manager for macOS:
- https://github.com/Homebrew/homebrew-core/pull/20229
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/asciidoctor.rb
- http://braumeister.org/formula/asciidoctor
So it would be nice to get the word out.
Do I need to also update the translations and http://asciidoctor.org/docs/install-asciidoctor-osx/, or maybe someone else would take care of those?

Mention Homebrew package manager in README

---

lib/asciidoctor/reader.rb
test/fixtures/outer-include.adoc
test/fixtures/subdir/inner-include.adoc
test/fixtures/subdir/middle-include.adoc
test/reader_test.rb

- match behavior of resolving local nested includes
- consistently set @dir on Reader to '.' if file is not defined

resolves #2506 resolve nested includes in remote documents relative to URI

---

data/locale/attributes-fr.adoc

Appendix must translate to Annexe, not Appendice. Appendice exists but has other meanings.

fix French translation of Appendix

---

.travis.yml

`gem uninstall -x --silent bundler` causes erros ..., so I removed the `before_install:` (but, I don't know why this settings was necessary ..., the original PR is https://github.com/asciidoctor/asciidoctor/pull/2528 ).
----
https://travis-ci.org/asciidoctor/asciidoctor/jobs/334344979
```
...
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 1.16.0
$ gem --version
2.7.4
1.25s$ if [ "`rvm current`" == "ruby-2.5.0" ]; then rvm use @global && gem uninstall -x --silent bundler && rvm use @ && gem install --silent bundler; fi
Using /home/travis/.rvm/gems/ruby-2.5.0 with gemset global
ERROR:  While executing gem ... (Gem::InstallError) …
```

Fix travis error (ruby-2.5.0, failed to uninstall bundler)

---

lib/asciidoctor/document.rb
test/api_test.rb

- when restoring attributes, duplicate header attributes
- allow header attributes to be restored an arbitrary number of times

resolves #2567 duplicate header attributes when restoring

---

data/stylesheets/asciidoctor-default.css

Pseudo-elements `::before` and `::after` require two dots before them.
[Mozilla docs for ::before](https://developer.mozilla.org/en-US/docs/Web/CSS/::before)

Small CSS fix.

---

data/stylesheets/asciidoctor-default.css
lib/asciidoctor/converter/html5.rb

- valid values are even, odd, all, and none
- not set by default; implies stripes on even rows
- requires support from stylesheet

resolves #1365 allow table stripes to be configured using stripe option on table

---

data/stylesheets/asciidoctor-default.css
features/xref.feature
lib/asciidoctor/converter/html5.rb
test/tables_test.rb

- add content class to div surrounding AsciiDoc cell content
- collapse bottom margin of last block in AsciiDoc table cell
- simplify margin collapsing on last paragraph in normal cell
- remove unused styles
- update tests

resolves #2568 collapse bottom margin of last block in AsciiDoc table cell

---

lib/asciidoctor/document.rb
lib/asciidoctor/path_resolver.rb
lib/asciidoctor/reader.rb

- add PathResolver#absolute_path? method
- isolate PathResolver#root? implementation for xmlhttprequest IO module
- add PathResolver#descends_from? helper
- initialize PathResolver to handle both both forward and backslashes in path
- always posixify target
- handle target with file:// prefix first
- don't modify target if it's a URL 
- enforce allow-uri-read restriction if target is a URL and doesn't descend from base_dir
- add file:// scheme to absolute path (xmlhttrequest IO module)
- resolve include path for top-level relative include
- resolve include path for nested relative include
- check allow-uri-read if nested include comes from a document w/ different origin as base_dir

resolves #2599 and #2602 correctly resolve includes in browser environment

---

lib/asciidoctor/extensions.rb
test/extensions_test.rb

- split impl of class_for_name by Ruby version
- add tests to verify correct error message is thrown when passed an illegal constant name
- add tests to verify top-level class is not resolved when namespaced class is requested

resolves #2622 raise clearer exception when extension class cannot be resolved

---

lib/asciidoctor/converter/docbook5.rb

Define source and manual refmiscinfo entries if the corresponding
attributes are defined.  For source, we need to define a dumb one
always; otherwise xmlto puts ugly "FIXME".

Add source and manual attrs for manpage

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/path_resolver.rb
test/document_test.rb
test/paths_test.rb

- resolve parent references in start path when resolving system path
- change PathResolver#expand_path to resolve parent references
- fix case where string literal is used instead of SLASH constant in PathResolver
- change partition_path to return two elements instead of three
- consolidate path split in partition_path
- enforce that start is inside of jail when absolute
- automatically recover if start is outside of jail by default
- allow target to bring resolved path back into jail even when start is outside
- fix descends_from? when base is /
- don't run File.expand_path on Dir.pwd
- allow target to bring resolved path under jail when start is outside jail

resolves #2642 resolve parent references in start path when resolving system path

---

lib/asciidoctor/cli/options.rb
test/options_test.rb

I'm packaging the latest asciidoctor version for Debian and right now it fails because of the test reading the man page form a non-standard location (which fails without trying the standard location).
This PR would check in the standard man page location (so it would not fail once the package is installed via distribution package installation).
The 1st case is when the installation has been done in a non-gzip way (can happen when you are building the package) and the other one is once you've installed the package.

Allow tests to run outside of the gem context with the manpage help topic

---

CHANGELOG.adoc
lib/asciidoctor/document.rb
test/attributes_test.rb

- support name!@, !name@, name!=@, and !name=@ syntax to soft unset attribute
- interpret false attribute value from API as soft unset
- allow modifier to be placed at end of name to soft set an attribute (e.g., icons@=font)
- add tests for all permutations of setting attributes from API
- minor refactoring

resolves #642 allow attribute to be soft unset from API or CLI

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

- allow footnote macro to be used to define or reference a footnote reference
* e.g., footnote:id[text] or footnote:id[]
- optimize detection for footnote* and indexterm* macros
- ignore footnote macro if missing both id and text
- deprecate footnoteref:[id] and footnoteref:[id,text] syntax

resolves #2347 allow footnote macro to define or reference a footnote reference

---

CHANGELOG.adoc
lib/asciidoctor/converter/manpage.rb
test/manpage_test.rb

- set text of MTO macro to blank if text matches e-mail address
- primarily used for implicit e-mail link
- previous check was failing due to mailto: prefix in value
- add test

resolves #2654 don't output e-mail address twice in manpage output

---

CHANGELOG.adoc
test/blocks_test.rb
test/substitutions_test.rb

Hi,
As asciimath is an optional gem (and not packaged in Debian yet), we maintain a patch that skips the tests that fail when asciimath is not installed: https://salsa.debian.org/ruby-team/asciidoctor/blob/master/debian/patches/skip-asciimath-test.patch
But if you only do the assert when the warning message about the gem is not present we would be able to avoid this.
Does that seem reasonable?
Thanks
Joseph

Allow the tests to run when asciimath is not installed

---

lib/asciidoctor/extensions.rb

This fixes the ChromeInineMacro -> ChromeInlineMacro and missing `do` keyword in the extensions.rb file. Only comments are affected, no functional changes.

Fix a few typos in extensions.rb

---

CHANGELOG.adoc
lib/asciidoctor/converter.rb
lib/asciidoctor/converter/factory.rb
test/converter_test.rb

- map backend info for custom converter to symbols instead of strings
- add opts argument to example in API doc for custom converter
- map handles? method for custom converter to respond_to? by default
- allow custom converter to declare that it supports templates

resolves #2619 allow custom converter to declare that it supports templates

---

CHANGELOG.adoc
lib/asciidoctor/parser.rb
test/sections_test.rb

- optimize section level validation
- warn if subsections are used where not allowed
- add tests to verify warnings when section title is out of sequence

resolves #2433 warn if nested sections are used where not allowed

---

CHANGELOG.adoc
features/xref.feature
lib/asciidoctor.rb
lib/asciidoctor/section.rb
test/sections_test.rb

- drop character refs and non-word chars (except for hyphen and space) instead of replacing with ID separator
- drop XML tags (but not the contents of the tag)
- replace spaces and hyphens with ID separator
- optimize logic in Section.generate_id method

resolves #794 drop XML tags, character refs, and non-word chars when generating ID for section

---

lib/asciidoctor/converter/html5.rb
lib/asciidoctor/parser.rb
test/sections_test.rb

- allow role to be set on document using block attribute (shorthand or longhand)
- assign role to docrole attribute on document
- add role to CSS classes on body in HTML5 output
- prefer ID defined in block attributes on document over ID defined inline (to be consistent w/ sections)

resolves #2387 allow role to be set on document

---

CHANGELOG.adoc
lib/asciidoctor/document.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/substitutors.rb
test/fixtures/other-chapters.adoc
test/links_test.rb
test/reader_test.rb

- change the includes key in the document catalog from a set to a hash
- don't track file included into the current file if included partially
- don't track file included into the current file unless it's AsciiDoc

resolves #2200 don't convert inter-document xref to internal anchor if target included partially

---

CHANGELOG.adoc
lib/asciidoctor/converter/html5.rb
test/blocks_test.rb
test/links_test.rb
test/substitutions_test.rb

- extract code to produces window and rel attributes into shared method
- don't look for window and link on document when resolving image link
- set rel=nofollow on anchor or linked image when nofollow option is set

resolves #2605 add support for rel=nofollow on links

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/reader.rb
test/fixtures/include-file.jsx
test/reader_test.rb

- allow any content after a tag directive if offset by a space
- add test to verify tag is found inside HTML inside a string in a source file

resolves #2369 change strategy for finding tags inside circumfix comments

---

data/locale/attributes-en.adoc
features/xref.feature
lib/asciidoctor/abstract_block.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/document.rb
lib/asciidoctor/extensions.rb
lib/asciidoctor/helpers.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/section.rb
test/extensions_test.rb
test/sections_test.rb

- number parts using roman numerals if the partnums attribute is set
- create dedicated module for managing roman numerals
- assign the value "Part" to the part-refsig attribute by default
- define the part-label attribute in the attributes-en.adoc data file
- add support for partnums and sectnums=all to create_section helper in extensions
- add partnums and sectnums=all scenarios to test for create_section helper
- change default value of numbered argument in Section#initialize to false

resolves #2298 add numbering for parts

---

CHANGELOG.adoc
features/xref.feature
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/substitutors.rb

- parse text of xref macro as attributes if attribute signature (equal sign) detected
- if role is set on xref, add it to class attribute of `<a>` element in HTML5 converter
- rename append_anchor_constraint_attrs to append_link_constraint_attrs
- add link contraint attributes to `<a>` element of interdoc xref
- rename variables in sub_inline_xrefs to be consistent with terminology

resolves #2381 parse attributes in xref macro if attribute signature is detected

---

CHANGELOG.adoc
lib/asciidoctor/parser.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/table.rb
test/api_test.rb
test/attributes_test.rb
test/blocks_test.rb
test/fixtures/lists.adoc
test/lists_test.rb
test/reader_test.rb
test/tables_test.rb

- fix incorrect line number on lists and tables (@seikichi)
- populate source_location on list items if sourcemap is enabled (@Mogztter)
- consolidate cursor data in Parser.next_block into an array
- consolidate definition of Cursor class
- split Reader#cursor and Reader#cursor_at methods
- introduce a mark system for tracking line numbers more accurately
- add Reader#mark method to mark position of cursor (store internally)
- add Reader#cursor_at_mark method to build Cursor from previously saved mark
- mark position of cursor after reading block attribute lines in Parser.next_block
- use Reader#cursor_at_mark to retrieve/record source location in Parser.next_block
- add cursor option to Reader#read_lines_until so unterminated block warning reports start location of block
- allow value of …

Accurately track source location for lists, list items, and tables

---

CHANGELOG.adoc
features/xref.feature
lib/asciidoctor/converter/html5.rb

- allow xrefstyle to be overridden per xref by assigning xrefstyle attribute on xref macro
- allow xrefstyle to be overridden in different parts of the document

resolves #2381 allow xrefstyle to be overridden per xref using the xrefstyle attribute

---

CHANGELOG.adoc
lib/asciidoctor/document.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/substitutors.rb
lib/asciidoctor/table.rb
test/tables_test.rb

- preserve leading indentation in AsciiDoc table cell if starts w/ newline
- adjust line number for AsciiDoc table cell document if contents starts w/ newline
- compute subs for table cell in Table:Cell#initialize; allow access to subs property on Table::Cell
- drop strip_text option when creating table cell (as it is implied when the attributes argument is defined)
- remove delegation when creating Cursor object 
- don't subtract 1 from length when slicing off first character of string

resolves #2712 preserve leading indentation in AsciiDoc table cell if starts w/ newline

---

CHANGELOG.adoc
lib/asciidoctor/abstract_block.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/table.rb
test/api_test.rb
test/fixtures/sample.asciidoc
test/tables_test.rb

- add source_location property to Table::Cell
- add file and lineno methods to Table::Cell
- when sourcemap option is enabled, set source_location property on cell
- mark first line of table so line number for first cell is correct
- add test to verify source_location information on table cell is correct

resolves #2705 populate source_location property on cell when sourcemap option enabled

---

lib/asciidoctor/substitutors.rb
test/links_test.rb
test/substitutions_test.rb

- parse text of link macro as attributes if text contains an equal sign
- parse text of mailto macro if text contains a comma
- remove use of linkattrs attributes from test suite

resolves #2059 enable linkattrs behavior implicitly (except in compat mode)

---

lib/asciidoctor.rb
lib/asciidoctor/parser.rb
test/lists_test.rb

- condense nested groups into a single flat group
- eagerly look for eol
- switch to 0-based repeat patterns
- remove unnecessary check for empty term text
- add test to verify ;; siblings are parsed using same rules

simplify regex for dlists

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/table.rb
test/lists_test.rb
test/tables_test.rb

- resolves #2257 catalog anchor at start of list item in an ordered or unordered list
- resolves #1675 catalog anchor at start of term in description list
- catalog anchor at start of table cell (unless the style is literal or asciidoc)

resolves #2257 catalog anchors at start of select list items and table cells

---

lib/asciidoctor/converter/docbook5.rb
test/blocks_test.rb

- if title is specified on open block, enclose open block content in a <formalpara> element
- otherwise, if id or role is specified, enclose open block content in a <para> element

resolves #2276 enclose open block if necessary in DocBook output

---

CHANGELOG.adoc
lib/asciidoctor/parser.rb
test/lists_test.rb

- only use text mode for parsing list text, not subsequent blocks
- don't call next_block when parsing list item if reader is empty

resolves #1926 use correct parse mode when parsing blocks for list item

---

lib/asciidoctor/callouts.rb
lib/asciidoctor/parser.rb
test/blocks_test.rb
test/lists_test.rb

- use cursor mark to track source location when parsing callout list
- improve warning message when callout refernce not found
- remove redundant end of file guard
- update tests

use cursor mark to track source location when parsing callout list

---

data/stylesheets/asciidoctor-default.css

The default HTML output works OK on Kindle ereaders, except that the margins and the line-height are too large. This PR adds rules to `asciidoctor-default.css` that resets the values of these just for `@media amzn-kf8`. Tested on Kindle Paperwhite.
(Change does not affect how the HTML output looks on other devices.)

Make default output Kindle-friendly

---

lib/asciidoctor/parser.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/substitutors.rb
test/attributes_test.rb
test/document_test.rb

- use single gsub pass
- remove dropped lines, if any, in post-processing step
- cache compliance values correctly
- optimize for single-line case
- add missing guards to check for attribute reference head

refactor sub_attributes

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css
lib/asciidoctor/converter/html5.rb
test/tables_test.rb

- only set white-space: nowrap on table caption if table has automatic width
- add fit-content CSS class to auto-width table

resolves #2392 only set nowrap style on table caption of auto-width table

---

lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb
test/links_test.rb

- disable in compat mode
- only process file extension when ref is source-to-source; leave other file extensions alone
- allow use of any known AsciiDoc file extension when hash is present in target
- only treat target of xref macro as interdoc xref if ends with .adoc
- change order of AsciiDoc file extensions in constant

make processing of interdoc xref more strict

---

CHANGELOG.adoc
lib/asciidoctor/converter/manpage.rb
test/manpage_test.rb

- use alternate groff macro \f(CR which does not conflict with / break AsciiDoc macros

resolves #2751 use alternate macro to switch on monospaced text

---

test/test_helper.rb

Hi,
Context: I am packaging the new version of asciidoctor for Debian and am trying to reduce the amount of custom stuffs we do there.
The idea of this PR is to be able to specify the tests when running them against an already installed environment.
With this PR we could either:
* use what we currently do if `ASCIIDOCTOR_LIB_PATH` is not set and the usual directory exists
* specify the `ASCIIDOCTOR_LIB_PATH` environment variable to say that the `lib/asciidoc.rb` is located in a given build directory (or in `/usr/lib/ruby/vendor_ruby/asciidoctor.rb` for example)
* try to load the gem if the usual location does not exist
Up to now we were changing the following line to `require 'asciidoctor'`:
```ruby
require File.join(ASCIIDOCTOR_PROJECT_DIR, 'lib', 'asciidoctor')
```
Having the …

Allow to specify the lib path via environment variable for the tests or load the gem directly

---

asciidoctor.gemspec

Hi,
This is the same idea as #2758.
Context: if you are in a build/autopkgtest environment that don't have the exact same directory structure as this, you end up having to write patch like https://salsa.debian.org/ruby-team/asciidoctor/blob/c7e30fd0010a0c6f90df492695e6d9731c0b2ce9/debian/patches/package-version.patch to change the lib directory.
This patch would allow us to use the environment variable `ASCIIDOCTOR_LIB_DIR` to specify the lib directory in those specific use cases.
Thanks
Joseph

Allow the usage of ASCIIDOCTOR_LIB_DIR in gemspec and Rakefile for loading the version

---

lib/asciidoctor.rb
test/extensions_test.rb

- allow custom macro name to contain hyphen as long as it's not the first character

resolves #2620 allow custom macro name to contain a hyphen

---

lib/asciidoctor.rb

Instead of looking at the whole line, then checking that the first character is not a dot, only look at the first character.

simplify regexp for setext section title

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/block.rb
lib/asciidoctor/list.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/substitutors.rb

Using .drop(0) is 1.5x as fast as .dup.

duplicate arrays using .drop(0) instead of .dup

---

CHANGELOG.adoc
Gemfile
asciidoctor.gemspec
lib/asciidoctor/converter/factory.rb
lib/asciidoctor/converter/template.rb
lib/asciidoctor/core_ext/1.8.7/concurrent/hash.rb
test/converter_test.rb

Because thread_safe is deprecated, as it was merged to concurrent-ruby.
> https://github.com/ruby-concurrency/thread_safe
> [DEPRECATED] Thread-safe collections for Ruby (merged with concurrent-ruby)
> https://github.com/ruby-concurrency/concurrent-ruby
> Collection classes that were originally part of the (deprecated) thread_safe gem:
> ...
> Hash A thread-safe subclass of Ruby's standard Hash.
> ...

Replace thread_safe with concurrent-ruby

---

lib/asciidoctor/abstract_node.rb

Fix an incorrect word. This was noticed on rubydoc.org while working
with the Asciidoctor API.

Trivial fix in abstract_node.rb comment

---

lib/asciidoctor/parser.rb
test/extensions_test.rb

- substitute attributes in target of custom block macro
- drop custom block macro if target references missing attribute and attribute-missing is drop-line

resolves #2839 substitute attributes in target of custom block macro

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/substitutors.rb
test/blocks_test.rb
test/lists_test.rb

- when icons are not enabled, preserve the comment guard in front of the callout number in verbatim blocks

resolves #1360 preserve comment guard on callout when icons not enabled

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/blocks_test.rb

- add support for range syntax (.. delimiter) to highlight attribute on source block
- add support for unbounded range to highlight attribute on source block
- add test for highlight attribute on source block

resolves #2918 add support for range syntax to highlight attribute on source block

---

CHANGELOG.adoc
asciidoctor.gemspec
lib/asciidoctor/converter/template.rb

prevent warning about invalid `:asciidoc` option when using custom templates with Slim 4

resolves #2928 prevent warning about invalid `:asciidoc` option

---

CHANGELOG.adoc
lib/asciidoctor/section.rb
test/sections_test.rb

- fix crash when child section of part is out of sequence and section numbering is enabled

resolves #2931 fix crash when child section of part is out of sequence

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/document.rb
test/fixtures/doctime-localtime.adoc
test/invoker_test.rb

- use timezone offset instead of OS dependent timezone string
- use UTC if offset is 0
- add tests

resolves #2770 use OS independent timezone in time attributes

---

CHANGELOG.adoc
lib/asciidoctor/converter/html5.rb
test/sections_test.rb

- add value of part-signifier attribute to beginning of title for numbered part
- add value of chapter-signifier attribute to beginning of title for numbered chapter
- change trailing delimiter of part number from period to colon

resolves #2738 use part-signifier and chapter-signifer, if set

---

CHANGELOG.adoc
lib/asciidoctor/document.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb
test/document_test.rb
test/substitutions_test.rb

- record the value of the imagesdir document attribute on the image node
- record the value of the imagesdir document attribute when registering the image

resolves #2779 track imagesdir on image node and in catalog

---

lib/asciidoctor/converter/html5.rb

Conditional Comments is unavailable on IE10 and more. So, I think we should remove the Conditional Comments.
e.g.
If we browse documents on intranet with IE, The Conditional Comments will be just a comment. Then, IE will work as older Document mode.

resolves #2983 remove conditional comments for IE

---

test/invoker_test.rb

Just lost 3 hours trying to figure out why, when running in a reproducible build environment, this timezone test was failing. Silly me! :laughing: 
Anyway, this patch allows you to run the tests properly in a reproducible builds environment (aka with `SOURCE_DATE_EPOCH` set).

Take in account SOURCE_DATE_EPOCH when testing against timezones

---

.travis.yml
CHANGELOG.adoc
Gemfile
data/stylesheets/asciidoctor-default.css
data/stylesheets/coderay-asciidoctor.css
lib/asciidoctor.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/document.rb
lib/asciidoctor/stylesheets.rb
lib/asciidoctor/substitutors.rb
lib/asciidoctor/syntax_highlighter.rb
lib/asciidoctor/syntax_highlighter/coderay.rb
lib/asciidoctor/syntax_highlighter/highlightjs.rb
lib/asciidoctor/syntax_highlighter/html_pipeline.rb
lib/asciidoctor/syntax_highlighter/prettify.rb
lib/asciidoctor/syntax_highlighter/pygments.rb
test/api_test.rb
test/blocks_test.rb
test/fixtures/source-block.adoc
test/invoker_test.rb
test/lists_test.rb
test/substitutions_test.rb
test/syntax_highlighter_test.rb

resolves #2106
- define the Asciidoctor::SyntaxHighlighter module to handle all aspects of syntax highlighting
- define built-in SyntaxHighlighter adapters for coderay, pygments, highlight.js, html-pipeline, and prettify
- move all embedded syntax highlighting logic into SyntaxHighlighter adapters
- allow SyntaxHighlighter adapter class to self register with a source highlighter name using register_for
- load SyntaxHighlighter adapters lazily (except for highlight.js and html-pipeline)
- add :syntax_highlighters and :syntax_highlighter_factory options to API to allow syntax highlighter resolution to be customized
- instantiate SyntaxHighlighter adapter once header is finalized if source-highlighter attribute is set on document and basebackend is html
- provide SyntaxHighlighter factory …

resolves #2106 make syntax highlighter pluggable

---

CHANGELOG.adoc
asciidoctor.gemspec
data/stylesheets/asciidoctor-default.css
lib/asciidoctor/rouge_ext.rb
lib/asciidoctor/syntax_highlighter.rb
lib/asciidoctor/syntax_highlighter/pygments.rb
lib/asciidoctor/syntax_highlighter/rouge.rb
test/syntax_highlighter_test.rb

resolves #1040
- add SyntaxHighlighter adapter implementation for Rouge
- change CSS class of line numbering table for Pygments and Rouge to linenotable
- reuse styles from default stylesheet to layout the line number column
- remove nested `<pre>` wrapper in Pygments output when line numbering is enabled and linenums mode is inline
- ensure syntax highlighter library is loaded when looking up base style
- add the rouge gem as a development dependency

resolves #1040 add syntax highlighter adapter for Rouge

---

CHANGELOG.adoc
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/parser.rb
test/attributes_test.rb

resolves #1944
- scope the role attribute to the block
- use attr/attr? to look up role with inheritance if necessary
- set role on document using role attribute instead of docrole attribute

resolves #1944 disable role inheritance 

---

CHANGELOG.adoc
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/attribute_list.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/list.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/substitutors.rb
lib/asciidoctor/table.rb
test/api_test.rb
test/attribute_list_test.rb
test/attributes_test.rb
test/lists_test.rb
test/parser_test.rb

- don't store the options attribute on the block once the options are parsed
- only store options as individual attributes (e.g., header-option)
- add an options method on AbstractNode to retrieve the set of option names
- store partial-option as empty string instead of true
- reference low-level option attribute internally

resolves #3051 drop the options attribute

---

CHANGELOG.adoc
lib/asciidoctor/cli/invoker.rb
lib/asciidoctor/cli/options.rb
lib/asciidoctor/substitutors.rb
man/asciidoctor.1
man/asciidoctor.adoc
test/invoker_test.rb
test/links_test.rb
test/options_test.rb
test/test_helper.rb

- use -v to set logger level to debug
- use -w to enable pedantic Ruby warnings (aka $VERBOSE = true)
- log possible invalid reference warnings at debug level
Note that -q still sets $VERBOSE = nil and is thus mutually exclusive with -w (in fact it overrides it).

resolves #3030 separate the -v and -w CLI flags

---

CHANGELOG.adoc
lib/asciidoctor.rb
test/sections_test.rb

resolves #3060
- although documented this way, the parser was checking for at least one word character, which is different

resolves #3060 require setext section title to have at least one alphanumeric character

---

lib/asciidoctor/document.rb
test/document_test.rb

Resolves #3064
The behavior is now consistent with either `convert_file` or `convert`.
It's also possible to override just  `docdate` or just `doctime`.
For instance we can use the document date but override the document time:
```rb
doc = Asciidoctor::Document.new [], input_mtime: ::Time.new(2019, 01, 02, 3, 4, 5, "+06:00"), attributes: {'doctime' => '10:00:00-0700'}
p doc.attr 'docdate' # '2019-01-02'
p doc.attr 'docyear' # '2019'
p doc.attr 'doctime' # '10:00:00-0700'
p doc.attr 'docdatetime' # '2019-01-02 10:00:00-0700'
```
In the example above, we override `doctime`.
As we can see, `docdatetime` is updated accordingly. The attributes `docdate` and `docyear` are using the document date (ie. `mtime`).
We can also just override `docdate`:
```rb
doc = Asciidoctor::Document.new [], …
```

Resolves #3064, compute docyear and docdatetime from docdate and doctime

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/links_test.rb

resolves #3021 
- always assume the target of a shorthand interdocument xref is a reference to an AsciiDoc document (source-to-source)
- if the target of a formal xref macro has a file extension, assume it's a path reference
- never assume the target of a formal xref macro is a path reference unless a file extension or fragment is present
- update tests

resolves #3021 assume any shorthand interdocument xref is a source-to-source reference

---

test/api_test.rb
test/blocks_test.rb
test/converter_test.rb
test/extensions_test.rb
test/lists_test.rb
test/logger_test.rb
test/manpage_test.rb
test/paragraphs_test.rb
test/parser_test.rb
test/reader_test.rb
test/substitutions_test.rb
test/syntax_highlighter_test.rb
test/tables_test.rb

- use chop instead of chomp to remove trailing newline from heredoc string
- document all uses of non-quoted squiggly heredoc to preserve indentation
- fix incorrect preparation of uniform indentation in list tests
- remove unnecessary uses of chomp

clean up newline handling in test suite

---

CHANGELOG.adoc
lib/asciidoctor/reader.rb
test/fixtures/parent-include-restricted.adoc
test/reader_test.rb

- enforce and report relative max include depth properly
- depth=0 on include directive disables nested includes (instead of depth=1)
- rename PreprocessorReader#exceeded_max_depth? to PreprocessorReader#exceeds_max_depth?
- change PreprocessorReader#exceeds_max_depth? to return nil if includes are disabled
- add api doc to PreprocessorReader#exceeds_max_depth?

enforce and report relative max include depth properly

---

CHANGELOG.adoc
features/xref.feature
lib/asciidoctor/document.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb
test/blocks_test.rb
test/document_test.rb
test/links_test.rb
test/lists_test.rb
test/sections_test.rb

* remove the logic that registers entries in :ids table of the document catalog
* don't attempt to compute the reftext when registering an xref (as this information is available from the referenced node and can be retrieved on demnd)
* add a Document#resolve_id method to look up ID by reference text (reftext or title); cache the result of lookups once parsing is complete
* always look for existing IDs using :refs table (when checking for a duplicate or whether a target exists)
* leave the :ids table empty to avoid breaking existing programs and extensions
* update tests
* add test to verify :ids table is always empty

resolves #3084 only store :refs, not :ids, in document catalog

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

resolves #3089
- fix crash caused by inline passthrough macro with the macros sub clearing the remaining passthrough placeholders

resolves #3089 fix crash caused by an inline passthrough with the macros sub

---

CHANGELOG.adoc
lib/asciidoctor/table.rb
test/api_test.rb
test/tables_test.rb

resolves #2963
- modify Cell class to extend AbstractBlock
- don't split paragraphs in table cell at line that resolves to blank and adjacent to other non-blank lines
- set level property on Cell and Column
- set content_model property on Cell
- define block? and inline? methods on Column that both return false

resolves #2963 modify Cell class to extend from AbstractBlock

---

CHANGELOG.adoc
lib/asciidoctor/parser.rb
test/document_test.rb

resolves #3106 
- apply header subs to doctitle attribute so it can safely be referenced in page
- simplify logic that checks for doctitle override

resolves #3106 apply header subs when assigning doctitle back to doctitle attribute

---

lib/asciidoctor/block.rb
lib/asciidoctor/list.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb

- don't attempt to detect listparagraph when locking in subs
- eagerly set default_subs to empty array
- consolidate fold first block logic
- remove unnecessary type checks when folding first block

optimize listparagraph processing

---

lib/asciidoctor.rb
lib/asciidoctor/parser.rb

- only store true values in DELIMITED_BLOCK_HEADS
- short-circuit check for fenced code block
- compare line with tip before checking for uniform line
- rename tl to tip_len for clarity
- consolidate conditions for checking for matching line and returning match data

refactor Parser.is_delimited_block?

---

CHANGELOG.adoc
lib/asciidoctor/abstract_block.rb
test/api_test.rb

resolves #2524
- find_by will discover table cells
- table cells can be selected by specifying the :table_cell context in the selector

resolves #2524 AbstractBlock#find_by finds table cells

---

lib/asciidoctor.rb
lib/asciidoctor/substitutors.rb
test/links_test.rb

- use capture to avoid running subsequent regular expression (UriTerminatorRx)
- only check if target ends with :// if target was modified
- update assertions to check that terminating character(s) got moved outside URL

refactor implicit link processing

---

docs/asciidoctor/modules/ROOT/pages/project/asciidoc-vs-markdown.adoc

* https://asciidoctor.org/docs/user-manual/#nested
- No leading space before the asterisks

fix(asciidoc-vs-markdown): use `ul` consistent with user manual

---

CHANGELOG.adoc
lib/asciidoctor/table.rb
test/tables_test.rb

resolves #3131 truncate with precision (instead of rounding) when computing abswidth for columns in DocBook output

---

CHANGELOG.adoc
lib/asciidoctor/abstract_block.rb
test/api_test.rb

- assume that true implies "accept"
- assume that false implies "skip"
- prefer :reject rather than :skip
- prefer :terminate instead of :skip_children

use terminology for find_by that better aligns with NodeFilter

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

- replace anchors and xrefs before footnotes
- fold sub_inline_anchors and sub_inline_xrefs into sub_macros
- drop found Hash

perform footnotes substitution last in macros substitution group

---

CHANGELOG.adoc
lib/asciidoctor/abstract_block.rb
lib/asciidoctor/section.rb
test/sections_test.rb

The first commit tries to make sure `numeral` is always a string, as it states in the RDoc.
The second commit changes the `numeral` of book parts from arabic to roman numerals.  The code used to make the translation only in `sectnum` method, leaving the actual attribute to arabic numeral.  Now the translation is done earlier.
These changes are part of the asciidoctor/asciidoctorj#549

Always store section numeral as string

---

lib/asciidoctor/converter.rb
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/converter/manpage.rb
test/converter_test.rb
test/document_test.rb

- prefix convert methods on built-in converters with convert_
- drop leading underscore from helper methods on built-in converters
- add adapter for older converters that rely on unprefixed convert methods
- use optimize convert handler dispatcher in HTML 5 converter
- only pass options to convert handler method if value is non-nil
- update RDoc

when resolving a convert method for a node, only consider methods prefixed with convert_

---

CHANGELOG.adoc
lib/asciidoctor/reader.rb
test/reader_test.rb

- use proper terminology in warning message for preprocessor directive
- add tests for unmatched and mismatched preprocessor directive

resolves #3165 use proper terminology in warning message about mismatched preprocessor directive

---

CHANGELOG.adoc
lib/asciidoctor/reader.rb
test/reader_test.rb

resolves #3161
- log warning if conditional expression in ifeval directive is invalid (#3161)
- drop lines that contain an invalid preprocessor directive (#3161)

resolves #3161 log warning if conditional expression in ifeval directive is invalid

---

lib/asciidoctor.rb
lib/asciidoctor/abstract_node.rb
lib/asciidoctor/converter.rb
lib/asciidoctor/converter/template.rb
lib/asciidoctor/core_ext.rb
lib/asciidoctor/core_ext/hash/merge.rb
lib/asciidoctor/document.rb
lib/asciidoctor/extensions.rb
lib/asciidoctor/inline.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb

- use .merge to duplicate Hash instead of .dup because it's much faster
- include patch for .merge to accept variable length argument list

use .merge to duplicate Hash instead of .dup

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/parser.rb
test/document_test.rb
test/parser_test.rb

- apply replacements substitution to author values
- only split multiple authors on semi-colon followed by space

resolves #2441 substitute replacements in author values used in document header

---

CHANGELOG.adoc
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/substitutors.rb
test/paragraphs_test.rb
test/substitutions_test.rb

- add support for see and see also relationships on index terms (shorthand and macro)
- parse attributes on indexterm* macros if text contains `=`

resolve #2047 add support for see and see also relationships on index terms

---

CHANGELOG.adoc
asciidoctor.gemspec

- bundle .yardopts so rubydoc.info selects correct README

resolves #3193 bundle .yardopts in RubyGem

---

CHANGELOG.adoc
lib/asciidoctor.rb
lib/asciidoctor/parser.rb
test/blocks_test.rb
test/sections_test.rb

- convert titles of cataloged block and section nodes containing attribute references eagerly to resolve attributes while in scope
- consolidate all processing of title and caption for block at end of next_block
- add tests to verify behavior

resolves #3202 convert cataloged titles containing attribute references eagerly

---

test/blocks_test.rb
test/substitutions_test.rb

The asciidoctor/helpers text was changed in a667772a ("resolves #1884
add detail to load error message if path is not gem name (PR #3195)",
2019-03-25).
This breaks test/blocks_test.rb and test/substitutions_test.rb,
resulting in a failure like:
--- expected
+++ actual
@@ -1 +1 @@
-"optional gem 'asciimath' is not installed. Functionality disabled."
+"optional gem 'asciimath' is not available. Functionality disabled."
Ensure the text in the asciimath tests matches what we output from
asciidoctor/helpers.

test: adjust message when asciimath is not available

---

CHANGELOG.adoc
lib/asciidoctor/abstract_block.rb
lib/asciidoctor/list.rb
lib/asciidoctor/parser.rb
test/lists_test.rb

- improve detection of an indented paragraph that's a continuation of the primary list text
- apply verbatim substitutions to all other literal paragraphs
- simplify the logic in the ListItem#fold_first method (and stop tracking continuation_connects_first_block)
- add tests to verify change

resolves #3205 apply verbatim substitutions to literal paragraphs attached to list item

---

CHANGELOG.adoc
lib/asciidoctor/converter/docbook5.rb
lib/asciidoctor/document.rb
lib/asciidoctor/reader.rb
lib/asciidoctor/substitutors.rb

resolves #3214
Workaround for this issue: https://github.com/opal/opal/issues/1961
Resolve a major issue in Asciidoctor.js 2.0.0 when using conditional expressions: https://github.com/oncletom/nodebook/pull/371
If necessary we could use this code only when running in Opal to avoid the variables assignments in other runtimes.

resolves #3214 extract as variables to workaround a scope conflict in Opal

---

CHANGELOG.adoc
lib/asciidoctor/helpers.rb
lib/asciidoctor/reader.rb
test/helpers_test.rb
test/reader_test.rb

- if final segment does not contain a dot, return original filename
- optimize assignments in PreprocessorReader#push_include
- add additional tests

Helpers.rootname should only consider final path segment when dropping file extension

---

.travis.yml

- Also: Removes an old setting from Travis. See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

CI: Use jruby-9.2.7.0, 2.4.6

---

lib/asciidoctor/converter/html5.rb
test/converter_test.rb

- replace . with CC_ALL
- also replace . with CC_ANY when matching dimension attribute

resolves #3261 fix regexp for SVG preamble so it works the same in Asciidoctor.js

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css

* prevent passthrough content from being cut off

resolves #3256 use smarter margin collapsing for AsciiDoc table cell content

---

CHANGELOG.adoc
lib/asciidoctor/converter.rb
lib/asciidoctor/syntax_highlighter.rb
test/converter_test.rb
test/syntax_highlighter_test.rb

- coerce symbol arguments to register_for to strings
- fill in missing API doc for register_for and register methods in SyntaxHighlighter module

resolves #3274 update register_for methods to accept symbol arguments

---

CHANGELOG.adoc
lib/asciidoctor/document.rb
lib/asciidoctor/parser.rb
lib/asciidoctor/substitutors.rb
test/document_test.rb

- register method accepts image as string
- register method reads value of imagesdir attribute from document

resolves #3283 register images in catalog correctly

---

lib/asciidoctor/syntax_highlighter.rb

Just a very small fix for the documentation of `SyntaxHighlighterFactory::create`.
The document is passed with the key `:document` instead of `:doc`:
https://github.com/asciidoctor/asciidoctor/blob/35c1f9a8f7c1cee310d6c1d1ad46ec5ae4702d54/lib/asciidoctor/document.rb#L1232-L1238

Fix documentation for options passed to SyntaxHighlighter constructor

---

.travis.yml
CHANGELOG.adoc
Gemfile
asciidoctor.gemspec
lib/asciidoctor/syntax_highlighter/rouge.rb
test/syntax_highlighter_test.rb
test/test_helper.rb

resolves #3336
* fixes compatibility with Rouge >= 3.4
* pass options to Rouge lexer using constructor instead of #lex method
* don't clobber cgi-style options on language when enabling start_inline option on the Rouge PHP lexer
* add tests for passing options to the Rouge lexer
* upgrade Rouge in development to 3.4.0

resolves #3336 fix how options are passed to the Rouge lexer

---

lib/asciidoctor.rb

Tested in Debian, this fixes our issue.
Thanks for the pointer @mojavelinux ! :) (I did the PR so that you didn't have to ;)
Closes: #3394

Fix autoload of the syntax highlighter in specific installations like Debian

---

data/locale/attributes-ru.adoc
data/locale/attributes-uk.adoc

Updated Russian (by @AlexanderZobkov) and Ukrainian (by @hedrok) translations for locale/attributes - to include new strings according to reference English attributes.
Add some strings, that were not translated before.
Changed "Последний раз обновлено" (Last time updated) into "Последнее обновление" (Last updated + a bit shorter) in Russian.
Changed "Зображення" (image) into "Рисунок" (technical/scientifical "figure") in Ukrainian. In general there are multiple terms that can mean "figure", however "Рисунок" is _usually_ recommended for technical documentation, e.g. see pt. 7.5.5 of Державний стандарт України. Документація. Звіти у сфері науки і техніки. Структура і правила оформлення. ДСТУ 3008-95 https://zakon.rada.gov.ua/rada/show/n0001217-96 (State Standard of Ukraine. Documentation. …

Update Russian and Ukrainian locale attributes translation

---

.travis.yml

When investigating issue https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/337 I found that the latest ruby version fixes some assertions, see https://github.com/jruby/jruby/pull/5693.
As the test suite of Asciidoctor runs without errors on this new JRuby release, I suggest an update of JRuby with this PR.

upgrade to jruby 9.2.8.0 fixes some bugs in assertions

---

CHANGELOG.adoc
lib/asciidoctor/converter/html5.rb
lib/asciidoctor/syntax_highlighter/coderay.rb
lib/asciidoctor/syntax_highlighter/pygments.rb
lib/asciidoctor/syntax_highlighter/rouge.rb
test/syntax_highlighter_test.rb

- move style tag for convert-time syntax highlighters into head
- invoke docinfo? :head method on syntax highlighter adapter after content has been converted

resolves #3462 move style tag for convert-time syntax highlighters into head

---

CHANGELOG.adoc
lib/asciidoctor/converter/html5.rb
test/converter_test.rb
test/fixtures/custom-backends/slim/html5-custom-outline/outline.html.slim

Allows plugging templates in to the html5 converter's "outline" by
replacing all direct calls to `convert_outline` with calls to the to the
conversion named `outline`.
Resolves #3491

resolves #3491 allow template to override outline

---

CHANGELOG.adoc
tasks/dependents.rake

This PR changes the build:dependents task to trigger the upstream build on Github instead of on Travis CI.
To get this running on TravisCI it is necessary to provision a Github auth token in the environment variable `GITHUB_TOKEN`.
This needs to have the `repo` scope.
Even though the tasks of triggering a build in Travis and Github are very similar, I duplicated the `:dependents` task, as I currently think it would make the logic too complex to distinguish between Github and Travis in the same task.
There are a few differences:
- Obviously a different URL to call
- The payload differs
- The request headers differ, including the auth token
- The response code for a successful trigger differs
Testing locally it seems like 2 `task`-s with the same name are called one after the other on `rake …

trigger build of AsciidoctorJ job running as GitHub Action

---

README.adoc

Add dates and link for the original AsciiDoc website and link to the older Python 2 GitHub repo.

Update dates and link for Stuart Rackham

---

tasks/dependents.rake

Asciidoctor.js now has a GitHub Action configured to run when a `repository_dispatch` event is received: https://github.com/asciidoctor/asciidoctor.js/blob/master/.github/workflows/build-upstream.yml
I took inspiration from AsciidoctorJ.
Pinging @robertpanzer for review :wink:

trigger Asciidoctor.js build running as GitHub Action

---

lib/asciidoctor/converter/manpage.rb

Most of man page viewing happens on the terminal, which
is monospaced anyway, but one can generate a PDF or PostScript
of a man page as well.
For example:
```console
$ man -Tps man > man.ps
```
or
```console
$ groff -Tps -t -man page.1 > page.ps
$ ps2pdf page.ps page.pdf # optional
```
In this case, if a man page was generated by asciidoctor, all the
blocks that are supposed to be using monospaced font, won't.
Fix is easy.

manpage: use monospaced font for literal and listing blocks

---

CHANGELOG.adoc
lib/asciidoctor/converter/manpage.rb
test/manpage_test.rb

when an ellipsis is at the start of line, is should be:
1. converted back to "..."
2. escaped so that the first period does not trigger a macro

resolves #3645 escape ellipsis at start of line in manpage output

---

data/locale/attributes-da.adoc
data/locale/attributes-es.adoc
data/locale/attributes-fr.adoc
data/locale/attributes-pl.adoc
data/locale/attributes-pt.adoc
data/locale/attributes-pt_BR.adoc

The translations for "part", "chapter", "section" and "listing" are missing in several languages.
This adds them for Danish, Spanish, French, Polish, Portuguese and Brazilian Portuguese.

Add missing Danish, Spanish, French, Polish and Portuguese attribute translations

---

data/locale/attributes-ca.adoc

* Fixes missing grave accent in `appendix-caption`.
* Adds missing Catalan values.
**Before merging,** I'd like double check `part-refsig`. What's its use?
Depending on it, I think it would be more appropiate to use "apartat", which is specific to designate a document seccion with a function and clearly separated, for examaple, by spacing, title and/or numbering. It also tends to be a short element, like a sub-section of a chapter. "Part" is a very generic term for anything, even without estructure or boundaries.
For exemple, you would say "the pre-installation chapter has 2 'apartats': hardware requirements and software requirements", or "All novels have 3 'parts'; introduction, development and conclusion"...but not the other way arround.

Adds missing Catalan attributes translation + fixes appendix

---

CHANGELOG.adoc
lib/asciidoctor/convert.rb
lib/asciidoctor/load.rb
test/fixtures/include-asciidoctor.rb
test/syntax_highlighter_test.rb

- define load, convert, load_file, convert_file as module methods (e.g., `def self.load`)
- avoids conflict between `Asciidoctor.load` and `Kernel.load` after calling `include Asciidoctor`

resolves #3625 don't use module_function to define entry point methods in API

---

CHANGELOG.adoc
lib/asciidoctor/converter/docbook5.rb
test/lists_test.rb

Was previously dropped - seemingly by accident - add to unit test.

docbook backend: restore reftext after anchor

---

.travis.yml

14.04 LTS has reached its end of support lifecycle and 20.04 LTS is still relatively new.

Use Ubuntu bionic (18.04 LTS) instead of trusty (14.04 LTS)

---

.travis.yml
tasks/dependents.rake

- use jobs instead of matrix
- run slower jobs first to reduce overall build time
- use a single regex to match TruffleRuby in commit message

use CI jobs and update match for TruffleRuby

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css

Is there any reason direction has to be set explicitly to LTR?
This can be inconvenient when trying to set the document direction to RTL.

Remove direction property from default stylesheet

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css

I found that applying border-collapse solves the disappearing cell borders. I tried to trace the history of this CSS settings, but wasn't able to determine the case why this was added here 58149743db9f59d4036879ff73da5b06eaf9ae9e
An example like this
```asciidoc
[options="header"]
|===
| Column 1 | Column 2 | Column 3
.2+|Content in a single cell that spans rows 1 and 2  |Cell in column 2, row 1 .2+|Content in a single cell that spans rows 1 and 2
|Cell in column 2, row 2
|===
```
that rendered before in Chrome like this using the asciidoctor CSS from master 
now renders like this

resolves #3793 don't apply border-collapse: separate to HTML for table blocks

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css

- this was done to avoid a double border, but that's since been solved by #3793

resolves #2563 don't remove right border on last table cell in row

---

CHANGELOG.adoc
lib/asciidoctor/converter/html5.rb
test/tables_test.rb

- consistently use frame-ends class rather than allowing it to be mixed based on input

resolves #3797 normalize frame value "topbot" to "ends" in HTML output

---

CHANGELOG.adoc
features/xref.feature
lib/asciidoctor/abstract_block.rb

* ignore xrefstyle in this case

resolves #3745 always use title as xreftext if target block has an empty caption

---

CHANGELOG.adoc
lib/asciidoctor/parser.rb
lib/asciidoctor/table.rb

- although Ruby 2.0 is not supported, it was working through 2.0.10, and the change that broke it was unnecesary
- additionally, track implicit header row assumption until table parsing is complete to avoid unnecessary assignments

resolves #3827 defer use of Ruby >= 2.3 constructs to restore compatibility with Ruby 2.0

---

CHANGELOG.adoc
lib/asciidoctor/converter/html5.rb
test/blocks_test.rb
test/substitutions_test.rb

- the width or height value could be coming from an extension, such as Asciidoctor Diagram

resolves #3829 fix crash when inlining an SVG if the explicit width or height value on image node is not a string

---

lib/asciidoctor/cli/options.rb

additionally, reword the description to use the terminology "input" instead of "source".

resolves #3870 use .adoc file extension in usage statement for CLI

---

docs/modules/api/pages/options.adoc

- correct symbol is `:extension_registry`
- there is no current documentation of the extension registry.  I'm working on it.

Correct extension registry errors in options.adoc

---

lib/asciidoctor/syntax_highlighter/rouge.rb

As a followup to the discussion on
https://discuss.asciidoctor.org/Interpret-links-or-other-AsciiDoc-syntax-only-in-specific-lines-of-a-source-block-td8499.html#a8517
this patch moves the lexer and formatter selection of the Rouge
syntax highlighter onto their own functions. This should make it easier
to extend the highlighter with custom lexers and/or highlighters without
having to replicate much of the logic in the highlight method.

resolves #3953 refactor creation of lexer and formatter

---

docs/modules/migrate/pages/ms-word.adoc

- Update pandoc command by removing deprecated --atx-headers. Use --markdown-headings=atx instead.
- Add pandoc command with docker to be able to use pandoc without installing it.
- Update pandoc command in general to work with the latest version as in https://pandoc.org/getting-started.html#step-6-converting-a-file

Docs: add a pandoc command using docker and update command.

---

.github/workflows/ci.yml

Before: 40s to install Ruby + Bundler and [around 9.5-10 min for bundle install on Windows + Ruby 3.0](https://github.com/asciidoctor/asciidoctor/runs/1635368583?check_suite_focus=true#step:10:1) (slowest platform currently, not sure why. Does it build libxslt from sources for Nokogiri instead of using prebuilt binary?)
After: [around 50s for Ruby + Bundler + bundle install combined on Windows + Ruby 3.0](https://github.com/slonopotamus/asciidoctor/runs/1637276403?check_suite_focus=true#step:7:1)
I'm not 100% happy with this change because we lose ability to do custom `bundle config` before installing deps, but benefits are pretty huge. @eregon do you want a feature request for this?

speedup CI by using Bundler cache

---

docs/modules/migrate/pages/confluence-xhtml.adoc

Fixes #3994 by modifying the instructions to match actual behavior of the provided groovy script.
Previous instructions were describing a behavior inconsistent with the groovy script provided. 
I've chosen to not change at all the script, only adapt the intructions for them to work.

resolves #3994 fix instructions for Confluence XHTML migration

---

CHANGELOG.adoc
lib/asciidoctor/parser.rb
lib/asciidoctor/reader.rb
test/document_test.rb
test/reader_test.rb

* don't drop leading and trailing empty lines in AsciiDoc include file
* skip empty lines before processing document header
* don't drop leading empty lines in main AsciiDoc file (defer until processing the document header)

resolves #3997 rollback change for #3470; skip empty lines before processing document header instead

---

docs/modules/ROOT/pages/docinfo.adoc

In #1720 a docinfo header was introduced, but this was not documented in the user manual.
Replaces https://github.com/asciidoctor/asciidoctor.org/pull/942

Add documentation for docinfo header

---

lib/asciidoctor/converter/semantic-html5.rb
test/fixtures/semantic-html5-scenarios/document-title-subtitle.adoc
test/fixtures/semantic-html5-scenarios/document-title-subtitle.html
test/fixtures/semantic-html5-scenarios/document-title-with-id-roles.adoc
test/fixtures/semantic-html5-scenarios/document-title-with-id-roles.html
test/fixtures/semantic-html5-scenarios/document-title-with-id.adoc
test/fixtures/semantic-html5-scenarios/document-title-with-id.html
test/fixtures/semantic-html5-scenarios/document-title-with-notitle.adoc
test/fixtures/semantic-html5-scenarios/document-title-with-notitle.html
test/fixtures/semantic-html5-scenarios/document-title.adoc
test/fixtures/semantic-html5-scenarios/document-title.html
test/semantic_html5_converter_test.rb

* Introduce a method to generate the header
* Introduce a method to generate the document title (title + subtitle)
* Generate a *simplified header* that includes the document title + subtitle on the embedded output
The implementation is *deliberately* incomplete to make it easier to review.
A more complete header will be implemented as part of https://github.com/asciidoctor/asciidoctor/issues/3967
Currently, `generate_*` methods can return `nil`.
More specifically, `generate_header` returns `nil` when `noheader` attribute is defined or when there's no header block. Similarly, `generate_document_title` returns `nil` when `notitle` attribute is defined.
Should we move conditions outside of these methods?
```rb
def generate_document_title node
doctitle = node.doctitle partition: true, …
```

ref #2749 distinguish title and subtitle

---

CHANGELOG.adoc
lib/asciidoctor/document.rb
test/attributes_test.rb
test/blocks_test.rb
test/sections_test.rb

resolves #4013 increment counter (but not the corresponding attribute) if attribute is locked
also resolves #4014 use attribute as seed value for counter even if not already registered as a counter

resolves #4013 increment counter even if attribute is locked

---

.github/workflows/ci.yml
CHANGELOG.adoc
lib/asciidoctor/load.rb
test/api_test.rb
test/invoker_test.rb
test/syntax_highlighter_test.rb
test/test_helper.rb

* run tests on JRuby 9.1 and 9.2 for Windows in CI
* don't run Pygments tests on JRuby 9.1 for Windows
* exclude tests that use run_command on JRuby 9.1 for Windows
* ensure mtime of input file honors TZ environment variable on JRuby for Windows

resolves #3550 run tests on JRuby for Windows in CI

---

CHANGELOG.adoc
lib/asciidoctor/parser.rb
test/document_test.rb

suppress missing attribute warning when applying substitutions to implicit document title to assign to doctitle attribute
author should assume there's an implicit attribute entry for doctitle directly after the document title (level-0 section title)

resolves #4024 suppress missing attribute warning when processing value for doctitle attribute

---

lib/asciidoctor/converter/docbook5.rb

add comment in DocBook converter as to why the `<link>` tag is used instead of `<xref>` when the reference has explicit link text

add comment in DocBook converter as to why link is used instead of xref

---

CHANGELOG.adoc
lib/asciidoctor/converter/docbook5.rb
test/links_test.rb

This is a follow-up to the fix for #4032, which also affected the DocBook output (though in a different way).

use document ID as linkend for self xref in DocBook output, generating one if necessary

---

lib/asciidoctor/converter/manpage.rb
test/manpage_test.rb

As you can see from the bug referenced in the preamble, the point is to
not convert \' to \(aq directly, because that only works in groff. To
make it portable \*(Aq should be used instead, and that will be
converted to \(aq in groff and ' elsewhere.
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=507673

manpage: fix apostrophe portability

---

docs/modules/tooling/pages/index.adoc

This extends the description of the IntelliJ AsciiDoc plugin. 
I updated the link to lead to the plugin's documentation and added a summary of the essential features. 
If you think this is too much and should be shortened, please let me know.

extend the description of the IntelliJ plugin

---

docs/modules/ROOT/pages/docinfo.adoc

Added the missing `shared-header` in the docinfo list ([Asciidoctor Docs > Docinfo Files > Enabling docinfo](https://docs.asciidoctor.org/asciidoctor/latest/docinfo/#enable)).

Fix documentation about shared-header

---

docs/modules/ROOT/pages/errors-and-warnings.adoc
docs/modules/ROOT/pages/whats-new.adoc
docs/modules/cli/pages/index.adoc
docs/modules/extensions/pages/inline-macro-processor.adoc
docs/modules/manpage-backend/pages/index.adoc
docs/modules/migrate/pages/asciidoc-py.adoc

- use "manpage" when referring to backend or doctype value
- use "man page" in all other cases
- improve description of warnings that pertain to manpage doctype
- revise documentation for manpage backend

resolves #4012 use man page and manpage terminology consistently in docs

---

README.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/install/pages/index.adoc
docs/modules/install/pages/macos.adoc

Hi there 👋
For the [last five years](https://github.com/macports/macports-ports/commits/master/textproc/asciidoctor/Portfile), asciidoctor has been available on [MacPorts](https://ports.macports.org/). It can be installed on macOS by running the following:
```
$ sudo port install asciidoctor
```
The project page can be found [here](https://ports.macports.org/port/asciidoctor/). Pre-built binaries and support is provided all the way from Big Sur to Snow Leopard from 12 years ago. I therefore thought that I'd add some documentation for this.
It goes without saying, but I also wanted to say thank you to the maintainers (particularly @mojavelinux) for providing bugfixes and updates for this amazing project all these years. Your work is greatly appreciated. 👍

Add MacPorts Documentation

---

lib/asciidoctor/cli/options.rb
man/asciidoctor.adoc
test/invoker_test.rb
test/options_test.rb

Fixes #3569
When writing an extension to asciidoctor the source location can be useful information. However it is not populated when the sourcmap option is not enabled which currently can only be done from the ruby API but not the CLI.
This pull request fixes that. The flag is -m because -s and -S are both taken already.

resolves #3569 add sourcemap flag to the CLI

---

CHANGELOG.adoc
lib/asciidoctor/abstract_block.rb
lib/asciidoctor/document.rb
lib/asciidoctor/section.rb
test/api_test.rb

resolves https://github.com/asciidoctor/asciidoctor.js/issues/850
Another solution would be to assign a default value (0) in the constructor.
Also, I believe that the internal method `assign_numeral` will fail if `@next_section_index` is `nil`. But since it's an internal method it should only be called on `Section`.

sections? returns false for anything that isn't itself a section

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css
src/stylesheets/asciidoctor.css

- also disable the outline drawn around the summary element when activated in Safari

resolves #4162 hide built-in marker on HTML summary element in Safari when using default stylesheet

---

CHANGELOG.adoc
lib/asciidoctor/converter/html5.rb
test/blocks_test.rb

* hash can be set using the hash attribute
* alternately, hash can be set in video ID following a forward slash

resolves #4176 allow hash to be specified for Vimeo video

---

data/locale/attributes-fr.adoc

This is just a suggestion for consistency across languages.
I'm a detail-oriented native French speaker and I'm available for exchanging on this topic if need be.
This is by no mean an urgent request and I'm sorry of how insignificant a contribution it is.
Thanks for the great tools and work!

resolves #4212 invert FR "caution" &  "warning" translations

---

lib/asciidoctor/converter.rb

The latest version of Opal will resolve `autoload` module/class at compile time.
However, the built-in template converter (`converter/template.rb`) relies on Ruby template engines and, as a result, cannot be compiled by Opal.
It's no use to try to create a JavaScript compatible version of the built-in template converter because Asciidoctor.js already provides a custom implementation when running in a Node.js environment: https://github.com/asciidoctor/asciidoctor.js/blob/master/packages/core/lib/asciidoctor/js/asciidoctor_ext/node/template.rb

Hide autoload converter/template from Opal

---

CHANGELOG.adoc
lib/asciidoctor/logging.rb
test/logger_test.rb

* update signature of the Logger constructor so both positional arguments and keyword arguments are passed to super constructor
* honor level and formatter keyword arguments passed to Logger constructor (even for Ruby 2.3)
* set logdev to $stderr if no arguments are passed to Logger constructor

resolves #4250 enhance Logger constructor to honor positional and keyword arguments

---

docs/modules/convert/pages/templates.adoc

It's inconsistent with what's below and should be `:template_dirs`.

Fix `:templates_dir` API option typo

---

README.adoc

The “简体中文” is the common expression for "Simplified Chinese" in Chinese.

clarify the link name

---

README-de.adoc
README-jp.adoc
README.adoc

supplement for #4278. I found that in [README-fr.adoc](https://github.com/asciidoctor/asciidoctor/blob/main/README-fr.adoc), It does not display language names in the local language like other readme documents, but only in French. Is this a French convention or document style?

Update the link name in readme

---

docs/modules/stem/pages/mathematical.adoc

asciidoctor-mathematical is working on macOS, at least when tested on my macOS Monterey system.

Update mathematical.adoc to reflect macOS support

---

Gemfile
asciidoctor.gemspec

AsciiDoctor currently requires Nokogiri `~> 1.10.0`, but Nokogiri v1.10 has been out of support since January 2021, and this requirement may [prevent AsciiDoctor tests from running on Ruby 3.1](https://github.com/flavorjones/mini_portile/issues/101#issuecomment-1223072639).
This PR updates the gemspec to allow for modern versions of Nokogiri.
A side benefit is that Nokogiri >= 1.11 ships [precompiled native gems](https://nokogiri.org/index.html#native-gems-faster-more-reliable-installation) for most platforms.

upgrade Nokogiri to latest version and add overrides for older Ruby versions

---

docs/modules/tooling/pages/index.adoc

This PR addresses issue #4362.
Added to the section on text editors:
```
[IMPORTANT]
====
The Atom editor's official site has announced that Atom is being sunset at the end of 2022.
See link:https://github.blog/2022-06-08-sunsetting-atom/[Sunsetting Atom] 
===
```

Added IMPORTANT: Atom is being sunset

---

CHANGELOG.adoc
docs/antora.yml
docs/modules/ROOT/pages/whats-new.adoc

- add section for Asciidoctor 2.0.18 to What's New
- minor rework of page description
- fix typos in CHANGELOG
- update attribute in antora.yml

update What's New for Asciidoctor 2.0.18

---

CHANGELOG.adoc
test/syntax_highlighter_test.rb

Adjust the pattern used by the `should gracefully fallback to default style if specified style not recognized` test to support rouge-4.1.0.
Upstream rouge commit 6f5aecd2 (Update GitHub theme, add dark mode (#1918), 2023-01-24) changed the CSS output.  Work with both old and new CSS.
resolves #4406

resolves #4406 fix test assertion for fallback Rouge stylesheet to be compatible with Rouge 4.1

---

docs/modules/api/pages/sourcemap.adoc
lib/asciidoctor/abstract_block.rb

... in the API documentation. The docs/ explain this, but a hint at the sourcemap option in the API docs would allow the reader to find that information.

Clarify that source_location is not tracked by default

---

CHANGELOG.adoc
lib/asciidoctor/substitutors.rb
test/links_test.rb

Test provided. 
As mentioned in #4393, the substitutor handles link with numeric character references incorrectly. This fixes it by avoiding matches of numeric character references with a regex.

resolves #4393 avoid matching numeric character references when searching for # in xref target

---

CHANGELOG.adoc
lib/asciidoctor/rx.rb
lib/asciidoctor/substitutors.rb
test/substitutions_test.rb

this change also fixes some incorrectly matched constrained passthrough and monospace cases, now covered by tests

resolves #4458 process constrained inline passthrough inside monospace span

---

docs/modules/convert/pages/templates.adoc

The original value for  `:url-slim:` no longer points to a page about the Slim template language.

Update templates.adoc with new URL for Slim

---

docs/modules/install/pages/ruby-packaging.adoc

To help new users, I thought the Bundler instructions could include the `bundle init` command. This generates a Gemfile with the default rubygems.org source [1].
[1] https://bundler.io/guides/gemfile.html#gemfiles

[Docs] Add command for generating default Gemfile

---

lib/asciidoctor/logging.rb

Upcoming ruby3.3 will have enhanced Logger class:
https://github.com/ruby/ruby/commit/194520f80e1cdb71faa055d731450855a1ddb8d1 which initializes newly added instance variables.
Without initializing such variables (in super class), now using subclass of Logger will cause exception.
To avoid this, first call super, then execute additional subclass initialization.
Closes #4493 .

resolves #4493 support ruby3.3 Logger by properly initialize super class

---

docs/modules/html-backend/pages/favicon.adoc

Just add the missing "ed" ending to a verb.

Fix trivial typo in favicon docs

---

CHANGELOG.adoc
data/reference/syntax.adoc
lib/asciidoctor/converter/html5.rb
test/blocks_test.rb

This PR adds basic support for Wistia to the `video::` macro, following a similar approach to how Youtube and Vimeo are currently supported. It supports some basic options (controlling looping behavior, autoplay, start time, dimensions, and muting), and uses an `iframe` embedding method.
It does include referencing an external script they recommend including with their embeds - while recommended, we don't strictly have to for things to work, so your call on whether you'd prefer we remove it.

resolves #4492 add Wistia support to the video macro

---

CHANGELOG.adoc
data/stylesheets/asciidoctor-default.css
src/stylesheets/asciidoctor.css

Consider the following document:
= Title
Foo.footnote:[Bar]
The link after Foo is underlined in active state but the link before Bar wasn't before this commit.
Note that the related
#footnotes .footnote a:first-of-type {
...
text-decoration: none;
...
}
is later in the stylesheet but this way the code is slightly smaller.
Fixes: https://github.com/asciidoctor/asciidoctor/issues/4530

resolves #4530 by underlining active footnote link in footnotes list

---

docs/modules/install/pages/linux-packaging.adoc

Previous URL redirects into 404.

docs: add correct Fedora package url

---

asciidoctor.gemspec

I noticed that the project already has a FUNDING.yml. This PR adds the `funding_uri` to your gemspec to help increase visibility using the `bundle fund` command in Bundler.

Add funding_uri to gemspec

---

docs/modules/extensions/pages/preprocessor.adoc

There is a small typo in the preprocessor extension docs.

Fix typo in preprocessor extension docs

---

docs/modules/extensions/pages/preprocessor.adoc

Front matter must start with `---`, see https://docs.asciidoctor.org/asciidoctor/latest/html-backend/skip-front-matter/.

fix front matter in preprocessor.adoc
